/* tslint:disable */
/* eslint-disable */
/**
 * Copyright: Copyright (c) 2016 by INT, Inc.  All rights reserved.<br>
 * Company: INT, Inc. <br>
 * INT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
import {_geo} from './geotoolkit.adv.module.js';
import {seismic} from './geotoolkit.seismic.adv.module.js';

export let seismic_analysis = (function (_geo) {var _geo=_geo||{};_geo.c.ra.gf=_geo.c.ra.gf||{};_geo.c.ra.gf.Ns=_geo.c.ra.gf.Ns||{};_geo.c.ra.gf.f=_geo.c.ra.gf.f||{};_geo.c.ra.gf.iF=_geo.c.ra.gf.iF||{};_geo.c.ra.gf.filters=_geo.c.ra.gf.filters||{};_geo.c.ra.gf.f.Odb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.util.ArrayOperations");b.M4a=function(a,b,e,d,f){e.set(a.subarray(b,b+f),d)};b.fill=function(a,b,e,d){for(;b<=e;b+=1)a[b]=d};return b}();
_geo.c.ra.gf.f.QWa=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.util.DataPadding");b.Pxb=function(a,b){return void 0!==b?this.GCc(a,b):this.HCc(a)};b.GCc=function(a,b){if(b!==this.Xtb(b))return null;var e=new window.Float32Array(b);e.set(a,0);return e};b.HCc=function(a){var b;b=this.Xtb(a.length);b=new window.Float32Array(b);b.set(a,0);return b};b.Xtb=function(a){return Math.pow(2,Math.ceil(Math.log(a)/Math.log(2)))};return b}();
_geo.c.ra.gf.f.GKb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.util.RemoveDC");b.ruc=function(a,b){var e,d,f,h,l;l=a.length;e=new window.Float32Array(l);d=void 0===b?0:b;f=_geo.c.ra.gf.iF.KHa.pSa(a);for(h=0;h<l;h+=1)e[h]=a[h]-f+d;return e};return b}();
_geo.c.ra.gf.f.Tgb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.util.Smoothing");b.YTb=function(a,b,e){var d,f,h,l,k;d=a.length;f=new window.Float32Array(d);h=e-1;e+=1;l=h+e;for(k=0;k<d;k++)f[k]=(a[k]*h+b[k]*e)/l;return f};b.m6a=function(a,g,e){var d,f,h,l,k,m;if(1===g)return a;if(0===g%2)return d=b.m6a(a,g-1,e),a=b.m6a(a,g+1,e),b.YTb(d,a,g);f=_geo.c.ra.gf.iF.KHa;h=a.length;l=new window.Float32Array(h);k=Math.floor(g/2);for(d=m=0;d<g;d++)m+=a[d];for(d=k;d<h-k;d++)l[d]=m/g,m-=
a[d-k],m+=a[d+k+1];g=Math.min(h-1,k);for(d=0;d<g;d++)l[d]=e?f.pSa(a,0,d+1):window.NaN;g=Math.max(h-k,1);for(d=h-1;d>=g;d--)l[d]=e?f.pSa(a,d-1,h-1):window.NaN;return l};b.job=function(a,g){var e,d,f,h,l,k,m,q,p,u,t;if(1===g)return a;if(0===g%2)return e=b.job(a,g-1),d=b.job(a,g+1),b.YTb(e,d,g);e=a.length;d=(g-1)/2;f=e+2*d;h=new window.Float32Array(f-2*d);l=new window.Float32Array(f);k=new window.Float32Array(f);f=new window.Float32Array(f);m=_geo.c.ra.gf.iF.KHa;q=_geo.c.ra.gf.f.Odb;q.M4a(a,0,l,0,e);
q.fill(f,0,d,l[0]);q.M4a(l,0,f,d,e);q.fill(f,e+d,e+2*d,l[e-1]);l=d+e;for(t=d;t<l;t+=1)p=t-d,u=t+d,k[p]=m.pSa(f,p,u);q.M4a(k,0,h,0,e);return h};return b}();
_geo.c.ra.gf.f.ELb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.util.StepPrecisionUtil");b.Z1b=function(a,g,e){var d,f;d=b.ICa(e);f=b.ICa(a);d=Math.max(d,f);a+=g*e;return 1E17<=d?a:Math.round(a*d)/d};b.sxc=function(a,g,e){return b.Z1b(a,Math.abs(g),Math.abs(e))};b.$1b=function(a,g,e){var d,f;d=b.ICa(e);f=b.ICa(a);d=Math.max(d,f);return 1E17<=d?Math.round((g-a)/e):Math.round((g-a)*d/(e*d))};b.t1b=function(a,g,e){if(g<a)throw Error("Can't calculate step number with min value "+
a+" and value "+g);return b.$1b(a,g,Math.abs(e))};b.txc=function(a,g,e){return b.t1b(a,g,e)+1};b.nxc=function(a){var b,e,d,f;b=0;e=1;d=a;for(f=Math.round(d);0<Math.abs(d-f);)b++,e*=10,d=a*e,f=Math.round(d);return b};b.ICa=function(a){var b,e,d;if(a===Number.POSITIVE_INFINITY||a===Number.NEGATIVE_INFINITY)throw Error("Can't compute step multiplier for "+a);b=1;e=a;d=Math.round(e);if(d===Number.MAX_VALUE)throw Error("Step is too big: "+a);for(;0<Math.abs(e-d);)b*=10,e=a*b,d=Math.round(e);return b};
b.xsc=function(a){var g=b.ICa(a);return Math.round(a*g)/g};return b}();
_geo.c.ra.gf.iF.KHa=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.maths.DataStatistics");b.max=function(a,b,e){var d;e=void 0===e?a.length:e+1;d=Number.MIN_VALUE;for(b=void 0===b?0:b;b<e;b+=1)a[b]>d&&(d=a[b]);return d};b.min=function(a,b,e){var d;e=void 0===e?a.length:e+1;d=Number.MAX_VALUE;for(b=void 0===b?0:b;b<e;b+=1)a[b]<d&&(d=a[b]);return d};b.PGc=function(a,b,e){var d;e=void 0===e?a.length:e+1;d=0;for(b=void 0===b?0:b;b<e;b+=1)d+=a[b];return d};b.pSa=function(a,b,e){var d,
f;e=void 0===e?a.length:e+1;f=d=0;for(b=void 0===b?0:b;b<e;b+=1)d+=a[b],f+=1;return d/f};b.QGc=function(a,b,e){var d;e=void 0===e?a.length:e+1;d=0;for(b=void 0===b?0:b;b<e;b+=1)d+=Math.abs(a[b]);return d};b.Ovc=function(a){return 0>a?Math.ceil(a):Math.floor(a)};return b}();
_geo.c.ra.gf.iF.aGb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.maths.ComplexMathUtils");b.lqc=function(a){return Math.sqrt(a.s7()*a.s7()+a.b7()*a.b7())};b.EBc=function(a,b){var e=a.s7()*b.s7()-a.b7()*b.b7(),d=a.s7()*b.b7()+a.b7()*b.s7();return new _geo.c.ra.gf.iF.AHa(e,d)};return b}();
_geo.c.ra.gf.iF.AHa=function(){function b(a,b){this.XS=this.tT=0;2===arguments.length?(this.tT=a,this.XS=b):1===arguments.length&&(a instanceof _geo.c.ra.gf.iF.AHa?(this.tT=a.s7(),this.XS=a.b7()):this.tT=a)}_geo.c.ja(b,"geotoolkit.seismic.analysis.maths.ComplexNumber");b.prototype.s7=function(){return this.tT};b.prototype.hbc=function(a){this.tT=a;return this};b.prototype.b7=function(){return this.XS};b.prototype.iac=function(a){this.XS=a;return this};b.prototype.toString=function(){var a=0<=this.XS?
"+":"-";return this.tT.toString()+a+Math.abs(this.XS).toString()+"i"};return b}();
_geo.c.ra.gf.iF.meb=function(){function b(a,b){1===arguments.length?a instanceof _geo.c.ra.gf.iF.meb?(this.tT=a.wub(),this.XS=a.gtb(),this.wk=a.ud()):a instanceof window.Float32Array?(this.tT=a.subarray(0,a.length),this.XS=new window.Float32Array(a.length),this.wk=a.length):(this.tT=new window.Float32Array(a),this.XS=new window.Float32Array(a),this.wk=a):(this.tT=a.subarray(0,a.length),this.XS=b.subarray(0,b.length),this.wk=a.length)}_geo.c.ja(b,"geotoolkit.seismic.analysis.maths.ComplexArray");b.prototype.get=
function(a){return new _geo.c.ra.gf.iF.AHa(this.tT[a],this.XS[a])};b.prototype.set=function(a,b){this.tT[b]=a.s7();this.XS[b]=a.b7();return this};b.prototype.wub=function(){return this.tT};b.prototype.gtb=function(){return this.XS};b.prototype.ud=function(){return this.wk};return b}();
_geo.c.ra.gf.Ns.QVa=function(){function b(a,b,e,d){this.cX=1;this.qr=this.dQb=0;this.setData(a,b,e,d)}_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.AbstractFFT");b.prototype.setData=function(a,b,e,d){var f;this.Pga=new window.Float32Array(0);this.yoa=new window.Float32Array(0);void 0===e||null===e||(0,window.isNaN)((0,window.parseFloat)(e))||(this.cX=e);e=void 0!==a&&null!==a&&1<a.length;f=void 0!==b&&null!==b&&1<b.length;e&&(this.dQb=void 0!==d&&null!==d&&!(0,window.isNaN)((0,window.parseFloat)(d))&&
d<a.length?d:a.length,this.Pga=_geo.c.ra.gf.f.QWa.Pxb(a));f&&(this.yoa=_geo.c.ra.gf.f.QWa.Pxb(b));e&&!f&&(a=this.Pga.length,this.yoa=new window.Float32Array(a));!e&&f&&(a=this.yoa.length,this.Pga=new window.Float32Array(a));this.qr=this.Pga.length;return this};b.prototype.tFa=function(a,b){this.Pga=a;this.yoa=b;return this};b.prototype.transform=_geo.c.WD;b.prototype.te=_geo.c.WD;b.prototype.oY=function(a){return!0===a?this.Pga:this.Pga.subarray(0,this.Pga.length)};b.prototype.c7=function(a){return!0===
a?this.yoa:this.yoa.subarray(0,this.yoa.length)};b.prototype.ud=function(){return this.qr};b.prototype.aca=function(){return this.dQb};b.prototype.Tsb=function(){return this.qr/2};b.prototype.Q0b=function(){return Math.log(this.qr)/Math.log(2)};b.prototype.KCa=function(){return.5/this.cX};b.prototype.bca=function(){return this.Tsb()};b.prototype.Zm=function(){return this.cX};b.prototype.Wka=function(a){this.cX=a;return this};b.prototype.f_b=function(){return this.KCa()/this.bca()};return b}();
_geo.c.ra.gf.Ns.Vgb=function(){function b(){}_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.SpectraCalculator");b.sob=function(a,b,e,d){var f,h;d=void 0!==d?d:a.length/2;f=new window.Float32Array(d);f[0]=a[0]*a[0]/(e*e);for(h=1;h<d;h+=1)f[h]=(a[h]*a[h]+b[h]*b[h])/(e*e);return f};b.eBa=function(a,b,e,d){var f,h;d=void 0!==d?d:a.length/2;f=new window.Float32Array(d);f[0]=a[0]/e;for(h=1;h<d;h+=1)f[h]=Math.sqrt(a[h]*a[h]+b[h]*b[h])/e;return f};b.irc=function(a,g,e,d,f){e=Math.floor(f/e);a=b.eBa(a,
g,d);return b.ZUa(a,e)};b.ZUa=function(a,b){var e=_geo.c.ra.gf.f.Tgb;return 1>=b?a:e.m6a(a,b,!0)};b.rob=function(a,b,e){var d,f;e=void 0!==e?e:a.length/2;d=new window.Float32Array(e);d[0]=Math.atan2(0,a[0]);for(f=1;f<e;f+=1)d[f]=Math.atan2(b[f],a[f]);return d};b.qob=function(a,g,e){a=b.rob(a,g,e);g=180/Math.PI;for(e=0;e<a.length;e+=1)a[e]*=g;return a};b.orc=function(a,g,e){a=b.qob(a,g,e);return b.kyb(a)};b.eDc=function(a){var g,e;a=b.lyb(a);g=180/Math.PI;for(e=0;e<a.length;e+=1)a[e]*=g;return a};
b.iOc=function(a,b){var e,d,f,h;e=b?Math.PI:180;d=new window.Float32Array(a.length);d[0]=a[0];for(h=0;h<a.length;h+=1)f=(a[h]+e)%(2*e),0>f&&(f+=2*e),d[h]=f-e;return d};b.lyb=function(a){var b,e,d,f;b=Math.PI;e=new window.Float32Array(a.length);e[0]=a[0];for(f=0;f<a.length;f+=1)d=(a[f]+b)%(2*b),0>d&&(d+=2*b),e[f]=d-b;return e};b.kyb=function(a){var b,e,d,f,h;b=0;e=180;d=new window.Float32Array(a.length);for(h=1;h<a.length;h+=1)f=a[h]-a[h-1],f>e&&(b-=2*e),f<-e&&(b+=2*e),d[h]=a[h]+b;return d};b.tob=
function(a,g,e,d){g=b.eBa(a,g,e,d);for(a=0;a<g.length;a+=1)g[a]=b.Bqc(g[a]);return g};b.Bqc=function(a){return 1E-15>=a?-200:20*Math.log(a)/Math.log(10)};b.tUb=function(a,g,e,d,f){a=b.eBa(a,g,e,d);g=Math.log(10);for(e=0;e<a.length;e+=1)if(a[e]=0!==f?20*Math.log(a[e]/(f+1E-15))/g:-120,(0,window.isNaN)(a[e])||!(0,window.isFinite)(a[e]))a[e]=-120;return a};return b}();
_geo.c.ra.gf.Ns.cea=function(){function b(a,b,d,f){_geo.c.ra.gf.Ns.QVa.call(this,a,b,d,f)}var a=_geo.c.ra.gf.Ns.Vgb;_geo.c.na(b,_geo.c.ra.gf.Ns.QVa);_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.AbstractFFTSpectra");b.prototype.yZ=function(){var a,b;a=this.oY(!0);b=this.c7(!0);return{n8:a,Q7:b,ge:null!==a&&void 0!==a&&null!==b&&void 0!==b}};b.prototype.g_b=function(){var b=this.yZ();return b.ge?a.eBa(b.n8,b.Q7,this.aca(),this.bca()):null};b.prototype.h_b=function(b){var e;e=this.yZ();if(!e.ge)return null;
e=a.eBa(e.n8,e.Q7,this.aca());b/=this.Zm();return a.ZUa(e,b)};b.prototype.Csb=function(){var b=this.yZ();return b.ge?a.qob(b.n8,b.Q7):null};b.prototype.Dsb=function(){var b=this.yZ();return this.yZ(b.n8,b.Q7)?a.rob(b.n8,b.Q7):null};b.prototype.i_b=function(){var b=this.yZ();return b.ge?a.kyb(this.Csb()):null};b.prototype.j_b=function(){var b=this.yZ();return b.ge?a.lyb(this.Dsb()):null};b.prototype.k_b=function(){var b=this.yZ();return b.ge?a.sob(b.n8,b.Q7,this.aca(),this.bca()):null};b.prototype.l_b=
function(){var b=this.yZ();return b.ge?a.tob(b.n8,b.Q7,this.aca(),this.bca()):null};b.prototype.m_b=function(b){var e=this.yZ();return e.ge?a.tUb(e.n8,e.Q7,this.aca(),this.bca(),b):null};b.prototype.n_b=function(b){var e;e=this.yZ();if(!e.ge)return null;e=a.tob(e.n8,e.Q7,this.aca(),this.bca());b=Math.floor(b/this.Zm());return a.ZUa(e,b)};b.prototype.o_b=function(b){var e;e=this.yZ();if(!e.ge)return null;e=a.sob(e.n8,e.Q7,this.aca(),this.bca());b=Math.floor(b/this.Zm());return a.ZUa(e,b)};return b}();
_geo.c.ra.gf.Ns.EHa=function(){function b(a,b,e,d){_geo.c.ra.gf.Ns.cea.call(this,a,b,e,d)}_geo.c.na(b,_geo.c.ra.gf.Ns.cea);_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.DFT");b.prototype.transform=function(){this.EHa(!1)};b.prototype.te=function(){this.EHa(!0)};b.prototype.EHa=function(a){var b,e,d,f,h,l,k,m,q,p;b=this.oY(!0);e=this.c7(!0);d=[];f=[];h=b.length;m=2*Math.PI/h;for(l=0;l<h;l+=1)d.push(0),f.push(0);for(q=0;q<h;q+=1)for(p=0;p<h;p+=1)l=Math.cos(p*q*m),k=-Math.sin(p*q*m),d[q]+=b[p]*
l-e[p]*k,f[q]+=b[p]*k+e[p]*l;if(a){e=f.slice(0);b=d.slice(0);for(l=0;l<h;l+=1)d[h-l-1]=b[l]/h,f[h-l-1]=e[l]/h;d.splice(0,0,d.splice(d.length-1,1)[0]);f.splice(0,0,f.splice(f.length-1,1)[0])}this.setData(d,f)};return b}();
_geo.c.ra.gf.Ns.w9=function(){function b(a,b,e,d){_geo.c.ra.gf.Ns.cea.call(this,a,b,e,d)}_geo.c.na(b,_geo.c.ra.gf.Ns.cea);_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.FFT");b.prototype.transform=function(){this.qKb(!1)};b.prototype.te=function(){this.qKb(!0)};b.prototype.qKb=function(a){var b,e,d,f,h,l,k,m,q;b=this.oY(!0);e=this.c7(!0);d=b.length;h=0;for(m=f=1;15>=m&&(h=m,f*=2,d!==f);m+=1);if(d===f){f=h;q=l=d;if(!0!==a)for(m=0;m<l;m+=1)e[m]=-e[m];h=Math.floor(f/3);if(0!==h)for(m=1;m<=h;m+=
1)k=1<<f-3*m,d=8*k,this.bkc(k,l,d,b,0,k,2*k,3*k,4*k,5*k,6*k,7*k,e,0,k,2*k,3*k,4*k,5*k,6*k,7*k);0===f-3*h-1?this.$jc(l,b,0,1,e,0,1):0<f-3*h-1&&this.akc(l,b,0,1,2,3,e,0,1,2,3);this.dfc(b,e,f,l,q,a);if(!0!==a)for(m=0;m<l;m+=1)e[m]=-e[m];else for(m=0;m<l;m+=1)b[m]/=q,e[m]/=q}};b.prototype.dfc=function(a,b,e,d,f){var h,l,k,m,q,p,u,t,r,n,v,w,x,y,B,A,C,D,E,F,J,H,G,K,M,O,L,N,I;h=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];for(d=0;d<=e;d+=1)h[d]=1<<e-d;y=h[0];x=h[1];w=h[2];v=h[3];n=h[4];r=h[5];t=h[6];u=h[7];p=h[8];q=
h[9];m=h[10];f=h[11];d=h[12];e=h[13];k=h[14];for(B=h=0;B<k;B+=1)for(A=B;A<e;A+=k)for(C=A;C<d;C+=e)for(D=C;D<f;D+=d)for(E=D;E<m;E+=f)for(F=E;F<q;F+=m)for(J=F;J<p;J+=q)for(H=J;H<u;H+=p)for(G=H;G<t;G+=u)for(K=G;K<r;K+=t)for(M=K;M<n;M+=r)for(O=M;O<v;O+=n)for(L=O;L<w;L+=v)for(N=L;N<x;N+=w)for(l=N;l<y;l+=x)h<l&&(I=a[h],a[h]=a[l],a[l]=I,I=b[h],b[h]=b[l],b[l]=I),h+=1};b.prototype.$jc=function(a,b,e,d,f,h,l){var k,m,q,p;for(m=0;m<a;m+=2)q=e+m,p=d+m,k=b[q]+b[p],b[p]=b[q]-b[p],b[q]=k,q=h+m,p=l+m,k=f[q]+f[p],
f[p]=f[q]-f[p],f[q]=k};b.prototype.akc=function(a,b,e,d,f,h,l,k,m,q,p){var u,t,r,n,v,w,x,y,B,A,C,D,E,F,J,H,G;for(B=0;B<a;B+=4)A=e+B,C=d+B,D=f+B,E=h+B,F=k+B,J=m+B,H=q+B,G=p+B,u=b[A]+b[D],t=b[A]-b[D],r=b[C]+b[E],n=b[C]-b[E],v=l[F]+l[H],w=l[F]-l[H],x=l[J]+l[G],y=l[J]-l[G],b[A]=u+r,l[F]=v+x,b[C]=u-r,l[J]=v-x,b[D]=t-y,l[H]=w+n,b[E]=t+y,l[G]=w-n};b.prototype.bkc=function(a,b,e,d,f,h,l,k,m,q,p,u,t,r,n,v,w,x,y,B,A){var C,D,E,F,J,H,G,K,M,O,L,N,I,Q,S,P,R,V,U,pa,Z,ba,fa,ma,ha,X,ca,sa,Ea,ta,qa,Fa,za,wa,Ga,ga,
xa,W,Y,Aa,T,oa,ia,la,Ca,Ua,Ta,va,ra,ua,Qa,Ia,Xa,Kb,Lb,Mb,lb,mb,nb,ob,pb,qb,$a,eb,Va,ab,bb,fb,cb,gb,Ja,Ya,Bb,yb,Cb,Db,Eb,da,Ba,Ra,sb,hb,ya,tb,db,ea;G=Math.SQRT1_2;K=2*Math.PI;C=K/e;for(O=0;O<b;O+=e)lb=f+O,mb=h+O,nb=l+O,ob=k+O,pb=m+O,qb=q+O,$a=p+O,eb=u+O,Va=r+O,ab=n+O,bb=v+O,fb=w+O,cb=x+O,gb=y+O,Ja=B+O,Ya=A+O,L=d[lb]+d[pb],N=d[mb]+d[qb],I=d[nb]+d[$a],Q=d[ob]+d[eb],S=d[lb]-d[pb],P=d[mb]-d[qb],R=d[nb]-d[$a],V=d[ob]-d[eb],U=t[Va]+t[cb],pa=t[ab]+t[gb],Z=t[bb]+t[Ja],ba=t[fb]+t[Ya],fa=t[Va]-t[cb],ma=t[ab]-
t[gb],ha=t[bb]-t[Ja],X=t[fb]-t[Ya],ca=L+I,sa=N+Q,Ea=L-I,ta=N-Q,qa=S-ha,Fa=P-X,za=S+ha,wa=P+X,Ga=U+Z,ga=pa+ba,xa=U-Z,W=pa-ba,Y=fa+R,Aa=ma+V,T=fa-R,oa=ma-V,E=G*(Fa-Aa),J=G*(Fa+Aa),F=G*(wa+oa),H=G*(oa-wa),d[lb]=ca+sa,t[Va]=Ga+ga,d[mb]=ca-sa,t[ab]=Ga-ga,d[nb]=Ea-W,t[bb]=xa+ta,d[ob]=Ea+W,t[fb]=xa-ta,d[pb]=qa+E,t[cb]=Y+J,d[qb]=qa-E,t[gb]=Y-J,d[$a]=za-F,t[Ja]=T-H,d[eb]=za+F,t[Ya]=T+H;for(M=1;M<a;M+=1)for(D=M*C,ia=Math.sin(D),ua=Math.cos(D),Qa=ua*ua-ia*ia,la=ua*ia+ua*ia,Ia=ua*Qa-ia*la,Ca=Qa*ia+la*ua,Xa=Qa*
Qa-la*la,Ua=Qa*la+Qa*la,Kb=Qa*Ia-la*Ca,Ta=Ia*la+Ca*Qa,Lb=Ia*Ia-Ca*Ca,va=Ia*Ca+Ia*Ca,Mb=Ia*Xa-Ca*Ua,ra=Xa*Ca+Ua*Ia,O=M;O<b;O+=e)lb=f+O,mb=h+O,nb=l+O,ob=k+O,pb=m+O,qb=q+O,$a=p+O,eb=u+O,Va=r+O,ab=n+O,bb=v+O,fb=w+O,cb=x+O,gb=y+O,Ja=B+O,Ya=A+O,L=d[lb]+d[pb],N=d[mb]+d[qb],I=d[nb]+d[$a],Q=d[ob]+d[eb],S=d[lb]-d[pb],P=d[mb]-d[qb],R=d[nb]-d[$a],V=d[ob]-d[eb],U=t[Va]+t[cb],pa=t[ab]+t[gb],Z=t[bb]+t[Ja],ba=t[fb]+t[Ya],fa=t[Va]-t[cb],ma=t[ab]-t[gb],ha=t[bb]-t[Ja],X=t[fb]-t[Ya],ca=L+I,sa=N+Q,Ea=L-I,ta=N-Q,qa=S-
ha,Fa=P-X,za=S+ha,wa=P+X,Ga=U+Z,ga=pa+ba,xa=U-Z,W=pa-ba,Y=fa+R,Aa=ma+V,T=fa-R,oa=ma-V,E=G*(Fa-Aa),J=G*(Fa+Aa),F=G*(wa+oa),H=G*(oa-wa),Ra=ca-sa,sb=Ga-ga,hb=Ea-W,ya=xa+ta,tb=Ea+W,db=xa-ta,ea=qa+E,Bb=Y+J,yb=qa-E,Cb=Y-J,Db=za-F,Eb=T-H,da=za+F,Ba=T+H,d[lb]=ca+sa,t[Va]=Ga+ga,d[mb]=Xa*Ra-Ua*sb,t[ab]=Xa*sb+Ua*Ra,d[nb]=Qa*hb-la*ya,t[bb]=Qa*ya+la*hb,d[ob]=Lb*tb-va*db,t[fb]=Lb*db+va*tb,d[pb]=ua*ea-ia*Bb,t[cb]=ua*Bb+ia*ea,d[qb]=Kb*yb-Ta*Cb,t[gb]=Kb*Cb+Ta*yb,d[$a]=Ia*Db-Ca*Eb,t[Ja]=Ia*Eb+Ca*Db,d[eb]=Mb*da-ra*
Ba,t[Ya]=Mb*Ba+ra*da};return b}();
_geo.c.ra.gf.Ns.Egb=function(){function b(a,b,e,d){_geo.c.ra.gf.Ns.w9.call(this,a,b,e,d)}_geo.c.na(b,_geo.c.ra.gf.Ns.w9);_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.RealFFT");b.prototype.mec=function(a){var b,e,d,f,h,l,k,m;if(this.Dmc!==a){this.Dmc=a;b=new window.Float32Array(a);d=new window.Float32Array(a);e=new window.Float32Array(a);f=new window.Float32Array(a);l=Math.PI/a;for(h=0;h<a;h+=1)k=l*h,m=.5*Math.sin(k),k=.5*Math.cos(k),b[h]=.5-m,d[h]=-k,e[h]=.5+m,f[h]=k;this.AQb=b;this.zQb=d;
this.CQb=e;this.BQb=f}};b.prototype.transform=function(){var a,b,e,d,f,h,l,k,m,q,p,u,t,r;a=this.oY(!0);b=a.length;e=b/2;this.mec(e);k=this.AQb;m=this.zQb;q=this.CQb;p=this.BQb;f=new window.Float32Array(e);h=new window.Float32Array(e);for(d=0;d<e;d+=1)f[d]=a[2*d],h[d]=a[2*d+1];this.tFa(f,h);_geo.c.ra.gf.Ns.w9.prototype.transform.call(this);f=this.oY(!0);h=this.c7(!0);a=new window.Float32Array(2*e+1);l=new window.Float32Array(2*e+1);a[0]=f[0]*k[0]-h[0]*m[0]+f[0]*q[0]+h[0]*p[0];l[0]=h[0]*k[0]+f[0]*m[0]+
f[0]*p[0]-h[0]*q[0];a[b]=a[0];l[b]=-l[0];for(d=1;d<e;d+=1)t=e-d,r=b-d,u=f[d]*k[d]-h[d]*m[d]+f[t]*q[d]+h[t]*p[d],t=h[d]*k[d]+f[d]*m[d]+f[t]*p[d]-h[t]*q[d],a[d]=u,l[d]=t,a[r]=u,l[r]=-t;a[e]=f[0]-h[0];l[e]=0;a=a.subarray(0,a.length-1);l=l.subarray(0,l.length-1);this.tFa(a,l);return this};b.prototype.te=function(){var a,b,e,d,f,h,l,k,m,q,p;p=this.oY(!0);f=this.c7(!0);a=p.length;e=a/2;this.mec(e);h=this.AQb;l=this.zQb;k=this.CQb;m=this.BQb;a=new window.Float32Array(e);b=new window.Float32Array(e);for(d=
0;d<e;d+=1)q=e-d,a[d]=p[d]*h[d]+f[d]*l[d]+p[q]*k[d]-f[q]*m[d],b[d]=f[d]*h[d]-p[d]*l[d]-p[q]*m[d]-f[q]*k[d];this.tFa(a,b);_geo.c.ra.gf.Ns.w9.prototype.te.call(this);a=this.oY(!0);b=this.c7(!0);p=new window.Float32Array(2*e);h=new window.Float32Array(2*e);for(d=0;d<e;d+=1)f=2*d,p[f]=a[d],p[f+1]=b[d];this.tFa(p,h)};return b}();
_geo.c.ra.gf.Ns.nLb=function(){function b(a,b,e,d){_geo.c.ra.gf.Ns.cea.call(this,a,b,e,d)}_geo.c.na(b,_geo.c.ra.gf.Ns.cea);_geo.c.ja(b,"geotoolkit.seismic.analysis.transforms.SimpleFFT");b.prototype.transform=function(){this.w9(!1)};b.prototype.te=function(){this.w9(!0)};b.prototype.gUb=function(a,b){var e,d,f,h;e=a;f=0;for(h=1;h<=b;h+=1)d=Math.floor(e/2),f=2*f+e-2*d,e=d;return f};b.prototype.w9=function(a){var b,e,d,f,h,l,k,m,q,p,u,t;p=0;b=this.oY(!0);e=this.c7(!0);d=b.length;f=d/2;h=Math.log(d)/
Math.log(2);l=h-1;if(!0===a)for(u=0;u<d;u+=1)e[u]=-e[u];for(t=1;t<=h;t+=1){for(;p<d;){for(u=1;u<=f;u+=1)k=this.gUb(p>>l,h),k=2*Math.PI*k/d,m=Math.cos(k),q=Math.sin(k),k=b[p+f]*m+e[p+f]*q,m=e[p+f]*m-b[p+f]*q,b[p+f]=b[p]-k,e[p+f]=e[p]-m,b[p]+=k,e[p]+=m,p+=1;p+=f}p=0;--l;f/=2}for(;p<d;)f=this.gUb(p,h),f>p&&(k=b[p],m=e[p],b[p]=b[f],e[p]=e[f],b[f]=k,e[f]=m),p+=1;if(!0===a)for(u=0;u<d;u+=1)b[u]/=d,e[u]/=-d};return b}();
_geo.c.ra.gf.filters.pJa=function(){function b(g,e,d,f,h,l){this.zMa=void 0!==l?l:!0;this.cX=void 0!==g?g:0;this.aga=new a.filters.qJa(e,d,f,h);this.d0=new a.Ns.Egb;this.dw=!0;this.hmb=new window.Float32Array(0);this.US=new window.Float32Array(0);this.NW=new window.Float32Array(0);this.Xo=this.hq=null;this.zs=b.gfa.gIa;this.K2a=!1;this.Pkb=this.ljb=this.Okb=this.kjb=this.XPb=this.u0=0}var a=_geo.c.ra.gf;_geo.c.ja(b,"geotoolkit.seismic.analysis.filters.TaperFilter");b.gfa={gIa:0,Uma:1};b.prototype.a7=
function(){return this.aga};b.prototype.fZ=function(a){this.aga.lh(a)||(this.aga.fZ(a),this.dw=!0);return this};b.prototype.Zm=function(){return this.cX};b.prototype.Wka=function(a){this.cX!==a&&(this.cX=a,this.d0.Wka(a),this.dw=!0);return this};b.prototype.dca=function(){return this.zMa};b.prototype.bva=function(a){this.zMa!==a&&(this.zMa=a,this.dw=!0);return this};b.prototype.apply=function(a,b){var d=void 0===b?a.length:b;this.hmb=new window.Float32Array(a.subarray(0,d),0);this.d0.setData(this.hmb,
null,this.Zm(),this.hmb.length);this.d0.transform();this.US=this.d0.oY(!0);this.NW=this.d0.c7(!0);var f=this.US.subarray(0,this.US.length);this.US=new window.Float32Array(f.length+2);this.US.set(f,0);f=this.NW.subarray(0,this.NW.length);this.NW=new window.Float32Array(f.length+2);this.NW.set(f,0);(this.dw||this.XPb!==d)&&0<this.d0.KCa()&&this.aga.ge()&&(this.XPb=d,this.uLb(this.US.length,this.zMa,100,2*this.d0.KCa()),this.uLb(this.NW.length,this.zMa,100,2*this.d0.KCa()),this.dw=!1);this.US=this.US.subarray(0,
this.US.length-2);this.NW=this.NW.subarray(0,this.NW.length-2);this.xLb(this.US,this.US.length);this.xLb(this.NW,this.NW.length);this.d0.setData(this.US,this.NW);this.d0.te();return new window.Float32Array(this.d0.oY(!0).subarray(0,d))};b.prototype.uLb=function(a,e,d,f){0<a&&1E-24<f?(this.zs=b.gfa.gIa,this.K2a=1,!0===e&&(this.K2a=0),this.u0=d,0>=this.u0&&(this.u0=1),1<this.u0&&(this.u0/=100),1<this.u0&&(this.u0=1),a=this.Qkc(f)):a=3;return a};b.prototype.Qkc=function(a){var e,d,f,h,l,k,m,q,p=0;m=
this.US.length;e=this.aga.Wra()/a;d=this.aga.Xra()/a;f=this.aga.Yra()/a;h=this.aga.Zra()/a;l=this.K2a;k=this.u0;a=this.zs;0>=k&&(k=1);1<k&&(k/=100);1<k&&(k=1);this.u0=k=1-k;this.Okb=this.kjb=0;this.ljb=m;this.Pkb=0;if(0>=m)return p;q=m-1;e=Math.floor(e*q+.5);d=Math.floor(d*q+.5);f=Math.floor(f*q+.5);h=Math.floor(h*q+.5);e>=m&&(e=m);d>=m&&(d=m);f>=m&&(f=m);h>=m&&(h=m);m=d-e;h-=f;this.kjb=e;this.Okb=m;0<=m&&(m!==this.size(this.hq)&&(this.hq=this.h8b(m,this.hq)),1===l?(e=1,q=k):(e=k,q=1),a===b.gfa.gIa&&
this.vLb(m,e,q,this.hq),a===b.gfa.Uma&&this.wLb(m,e,q,this.hq));this.ljb=f;this.Pkb=h;0<=h&&(h!==this.size(this.Xo)&&(this.Xo=this.h8b(h,this.Xo)),1===l?(e=k,q=1):(e=1,q=k),a===b.gfa.gIa&&this.vLb(h,e,q,this.Xo),a===b.gfa.Uma&&this.wLb(h,e,q,this.Xo));return p};b.prototype.vLb=function(a,b,d,f){var h,l,k;l=Math.PI;h=a+2;2>h&&(h=2);d=(d-b)/2;h=l/(h-1);for(k=0;k<a;k+=1)l=h*k,f[k]=b+d*(1-Math.cos(l))};b.prototype.wLb=function(a,b,d,f){var h,l,k,m;k=Math.PI/2;h=a;2>h&&(h=2);l=d-b;h=k/(h-1);if(d<=b)for(m=
0;m<a;m+=1)d=h*m,f[m]=b+l*(1-Math.cos(d));else for(m=0;m<a;m+=1)d=k-h*m,f[m]=b+l*Math.cos(d)};b.prototype.xLb=function(a,b){var d,f,h,l,k,m,q,p,u;d=this.K2a;f=this.u0;l=this.kjb;k=this.Okb;m=this.ljb;h=this.Pkb;k=l+k;q=m+h;h=b;if(0<l&&1!==d)for(u=0;u<l;u+=1)u<h&&(a[u]*=f);if(l<k)for(p=0,u=l;u<k;u+=1)l=this.hq[p],0<=u&&u<h&&(a[u]*=l),p+=1;if(k<m&&1===d)for(u=k;u<=m;u+=1)0<=u&&u<h&&(a[u]*=f);if(m<q)for(p=0,u=m;u<q;u+=1)l=this.Xo[p],0<=u&&u<h&&(a[u]*=l),p+=1;if(q<b-1&&1!==d)for(u=q;u<b;u+=1)0<=u&&(a[u]*=
f)};b.prototype.size=function(a){return void 0===a||null===a?0:a.length};b.prototype.h8b=function(a,b){var d=new window.Float32Array(a);null!==b&&(b.length<=a?d.set(b,0):d.set(b.subarray(0,a)));return d};return b}();
_geo.c.ra.gf.filters.YLb=function(){function b(b){this.ME=new a.filters.pJa(0,10,20,60,70,!0);b=g.tdb(b,"TaperFilter");g.call(this,b);this.Un(b)}var a=_geo.c.ra.gf,g=_geo.c.ra.Nf.xq.HM;_geo.c.ja(b,"geotoolkit.seismic.analysis.filters.TaperFilterProcess");_geo.c.na(b,g);_geo.c.ra.Nf.xq.YIa.register("Filter",b);b.prototype.a7=function(){return this.ME.a7()};b.prototype.fZ=function(a){this.ME.a7().lh(a)||(this.ME.fZ(a),this.ma());return this};b.prototype.bva=function(a){this.ME.dca()!==a&&(this.ME.bva(a),
this.ma());return this};b.prototype.dca=function(){return this.ME.dca()};b.prototype.Ah=function(){var a=g.prototype.Ah.call(this);return a&&this.ME.a7().ge()};b.prototype.Yl=function(){var a,b;a=g.prototype.Yl.call(this);b=this.ME.a7();a.sampleRate=this.ME.Zm();a.passFlag=this.ME.dca();a.f1=b.Wra();a.f2=b.Xra();a.f3=b.Yra();a.f4=b.Zra();return a};b.prototype.Un=function(a){var d,f;g.prototype.Un.call(this,a);if(null===a||void 0===a)throw Error("null reference exception");a instanceof b&&(a=a.get());
this.ME.Wka(this.verify(a.sampleRate,this.ME.Zm()));this.ME.bva(this.SGa(a.passFlag,this.ME.dca()));d=this.ME.a7();f=new _geo.c.ra.gf.filters.qJa;f.Yab(this.verify(a.f1,d.Wra()));f.Zab(this.verify(a.f2,d.Xra()));f.$ab(this.verify(a.f3,d.Yra()));f.abb(this.verify(a.f4,d.Zra()));this.ME.fZ(f);this.ma();return this};b.prototype.gl=function(a,b,f,g){return this.Ah()?(0===this.ME.Zm()&&this.ME.Wka(b.Zm()),g.set(this.ME.apply(f,f.length)),!0):!1};return b}();
_geo.c.ra.gf.filters.qJa=function(){function b(a,b,e,d){this.G0a=this.WKa=this.VKa=this.UKa=0;null!==a&&void 0!==a&&this.fZ(a,b,e,d)}_geo.c.ja(b,"geotoolkit.seismic.analysis.filters.TaperFrequencyBoundary");b.prototype.fZ=function(a,b,e,d){var f=a instanceof _geo.c.ra.gf.filters.qJa;this.Yab(f?a.Wra():a);this.Zab(f?a.Xra():b);this.$ab(f?a.Yra():e);this.abb(f?a.Zra():d);return this};b.prototype.ge=function(){return 0<=this.UKa&&this.UKa<=this.VKa&&this.VKa<=this.WKa&&this.WKa<=this.G0a};b.prototype.lh=
function(a){return this.UKa===a.Wra()&&this.VKa===a.Xra()&&this.WKa===a.Yra()&&this.G0a===a.Zra()};b.prototype.Wra=function(){return this.UKa};b.prototype.Yab=function(a){this.UKa=a;return this};b.prototype.Xra=function(){return this.VKa};b.prototype.Zab=function(a){this.VKa=a;return this};b.prototype.Yra=function(){return this.WKa};b.prototype.$ab=function(a){this.WKa=a;return this};b.prototype.Zra=function(){return this.G0a};b.prototype.abb=function(a){this.G0a=a;return this};return b}();
(function(){var b="geotoolkit",a="seismic",g=_geo.c.hx,e=_geo.c.gx,d=null,f=null;g(b+"."+a+".analysis.util.ArrayOperations",_geo.c.ra.gf.f.Odb);g(b+"."+a+".analysis.util.ArrayOperations.arrayCopy",(f=_geo.c.ra.gf.f.Odb).M4a);g(b+"."+a+".analysis.util.ArrayOperations.fill",f.fill);g(b+"."+a+".analysis.util.DataPadding",_geo.c.ra.gf.f.QWa);g(b+"."+a+".analysis.util.DataPadding.padTrace",(f=_geo.c.ra.gf.f.QWa).Pxb);g(b+"."+a+".analysis.util.DataPadding.getNextPowerOf2",f.Xtb);g(b+"."+a+".analysis.util.RemoveDC",
_geo.c.ra.gf.f.GKb);g(b+"."+a+".analysis.util.RemoveDC.deTrend",_geo.c.ra.gf.f.GKb.ruc);g(b+"."+a+".analysis.util.Smoothing",_geo.c.ra.gf.f.Tgb);g(b+"."+a+".analysis.util.Smoothing.fastSmooth",(f=_geo.c.ra.gf.f.Tgb).m6a);g(b+"."+a+".analysis.util.Smoothing.boxcarSmooth",f.job);g(b+"."+a+".analysis.util.StepPrecisionUtil",_geo.c.ra.gf.f.ELb);g(b+"."+a+".analysis.util.StepPrecisionUtil.getRelativeLineValue",(f=_geo.c.ra.gf.f.ELb).Z1b);g(b+"."+a+".analysis.util.StepPrecisionUtil.getNormalizedLineValue",
f.sxc);g(b+"."+a+".analysis.util.StepPrecisionUtil.getRelativeStepIndex",f.$1b);g(b+"."+a+".analysis.util.StepPrecisionUtil.getNormalizedStepIndex",f.t1b);g(b+"."+a+".analysis.util.StepPrecisionUtil.getNormalizedStepCount",f.txc);g(b+"."+a+".analysis.util.StepPrecisionUtil.getMinimumFractionDigits",f.nxc);g(b+"."+a+".analysis.util.StepPrecisionUtil.getNormalizedStepMultiplier",f.ICa);g(b+"."+a+".analysis.util.StepPrecisionUtil.convertFloatStepToDouble",f.xsc);g(b+"."+a+".analysis.maths.DataStatistics",
_geo.c.ra.gf.iF.KHa);g(b+"."+a+".analysis.maths.DataStatistics.max",(f=_geo.c.ra.gf.iF.KHa).max);g(b+"."+a+".analysis.maths.DataStatistics.min",f.min);g(b+"."+a+".analysis.maths.DataStatistics.sum",f.PGc);g(b+"."+a+".analysis.maths.DataStatistics.mean",f.pSa);g(b+"."+a+".analysis.maths.DataStatistics.sumAbs",f.QGc);g(b+"."+a+".analysis.maths.DataStatistics.fix",f.Ovc);g(b+"."+a+".analysis.maths.ComplexMathUtils",_geo.c.ra.gf.iF.aGb);g(b+"."+a+".analysis.maths.ComplexMathUtils.absCmplx",(f=_geo.c.ra.gf.iF.aGb).lqc);
g(b+"."+a+".analysis.maths.ComplexMathUtils.multCmplx",f.EBc);g(b+"."+a+".analysis.maths.ComplexNumber",(f=_geo.c.ra.gf.iF).AHa);e(d=_geo.c.ra.gf.iF.AHa.prototype,"getReal",d.s7,{s7:0});e(d,"setReal",d.hbc,{hbc:0});e(d,"getImag",d.b7,{b7:0});e(d,"setImag",d.iac,{iac:0});e(d,"toString",d.toString,{toString:0});g(b+"."+a+".analysis.maths.ComplexArray",f.meb);e(d=_geo.c.ra.gf.iF.meb.prototype,"get",d.get,{get:0});e(d,"set",d.set,{set:0});e(d,"getRealArray",d.wub,{wub:0});e(d,"getImagArray",d.gtb,{gtb:0});
e(d,"getLength",d.ud,{ud:0});g(b+"."+a+".analysis.transforms.AbstractFFT",(f=_geo.c.ra.gf.Ns).QVa);e(d=_geo.c.ra.gf.Ns.QVa.prototype,"setData",d.setData,{setData:0});e(d,"setDataUnsafe",d.tFa,{tFa:0});e(d,"transform",d.transform,{transform:0});e(d,"inverseTransform",d.te,{te:0});e(d,"getRealComponents",d.oY,{oY:0});e(d,"getImaginaryComponents",d.c7,{c7:0});e(d,"getLength",d.ud,{ud:0});e(d,"getNumberNonZeroSamples",d.aca,{aca:0});e(d,"getHalfLength",d.Tsb,{Tsb:0});e(d,"getLog2Length",d.Q0b,{Q0b:0});
e(d,"getNyquist",d.KCa,{KCa:0});e(d,"getNyquistLength",d.bca,{bca:0});e(d,"getSampleRate",d.Zm,{Zm:0});e(d,"setSampleRate",d.Wka,{Wka:0});e(d,"getFDSampleRate",d.f_b,{f_b:0});g(b+"."+a+".analysis.transforms.SpectraCalculator",f.Vgb);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcPower",(f=_geo.c.ra.gf.Ns.Vgb).sob);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcAmplitude",f.eBa);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcAmplitudeSmoothed",f.irc);g(b+"."+a+".analysis.transforms.SpectraCalculator.smoothSpectrum",
f.ZUa);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcPhaseInRadians",f.rob);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcPhaseInDegrees",f.qob);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcUnWrappedPhaseInDegrees",f.orc);g(b+"."+a+".analysis.transforms.SpectraCalculator.phaseUnwrapRadToDeg",f.eDc);g(b+"."+a+".analysis.transforms.SpectraCalculator.phaseUnwrapRadians",f.lyb);g(b+"."+a+".analysis.transforms.SpectraCalculator.phaseUnwrapDegrees",f.kyb);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcPowerDb",
f.tob);g(b+"."+a+".analysis.transforms.SpectraCalculator.calcPowerDbNormalized",f.tUb);g(b+"."+a+".analysis.transforms.AbstractFFTSpectra",(f=_geo.c.ra.gf.Ns).cea);e(d=_geo.c.ra.gf.Ns.cea.prototype,"getFFTAmplitude",d.g_b,{g_b:0});e(d,"getFFTAmplitudeSmooth",d.h_b,{h_b:0});e(d,"getFFTPhaseDegrees",d.Csb,{Csb:0});e(d,"getFFTPhaseRadians",d.Dsb,{Dsb:0});e(d,"getFFTPhaseInDegreesUnWrapped",d.i_b,{i_b:0});e(d,"getFFTPhaseInRadiansUnWrapped",d.j_b,{j_b:0});e(d,"getFFTPower",d.k_b,{k_b:0});e(d,"getFFTPowerInDb",
d.l_b,{l_b:0});e(d,"getFFTPowerInDbNormalized",d.m_b,{m_b:0});e(d,"getFFTPowerInDbSmoothed",d.n_b,{n_b:0});e(d,"getFFTPowerSmoothed",d.o_b,{o_b:0});g(b+"."+a+".analysis.transforms.DFT",f.EHa);e(d=_geo.c.ra.gf.Ns.EHa.prototype,"transform",d.transform,{transform:0});e(d,"inverseTransform",d.te,{te:0});g(b+"."+a+".analysis.transforms.FFT",f.w9);e(d=_geo.c.ra.gf.Ns.w9.prototype,"transform",d.transform,{transform:0});e(d,"inverseTransform",d.te,{te:0});g(b+"."+a+".analysis.transforms.RealFFT",f.Egb);e(d=
_geo.c.ra.gf.Ns.Egb.prototype,"transform",d.transform,{transform:0});e(d,"inverseTransform",d.te,{te:0});g(b+"."+a+".analysis.transforms.SimpleFFT",f.nLb);e(d=_geo.c.ra.gf.Ns.nLb.prototype,"transform",d.transform,{transform:0});e(d,"inverseTransform",d.te,{te:0});g(b+"."+a+".analysis.filters.TaperFilter",_geo.c.ra.gf.filters.pJa);g(b+"."+a+".analysis.filters.TaperFilter.TaperCosine",_geo.c.ra.gf.filters.pJa.gfa);g(b+"."+a+".analysis.filters.TaperFilter.TaperCosine.Half",(f=_geo.c.ra.gf.filters.pJa.gfa).gIa);
g(b+"."+a+".analysis.filters.TaperFilter.TaperCosine.Quarter",f.Uma);e(d=_geo.c.ra.gf.filters.pJa.prototype,"getFrequencyBoundary",d.a7,{a7:0});e(d,"setFrequencyBoundary",d.fZ,{fZ:0});e(d,"getSampleRate",d.Zm,{Zm:0});e(d,"setSampleRate",d.Wka,{Wka:0});e(d,"getPassFlag",d.dca,{dca:0});e(d,"setPassFlag",d.bva,{bva:0});e(d,"apply",d.apply,{apply:0});g(b+"."+a+".analysis.filters.TaperFilterProcess",(f=_geo.c.ra.gf.filters).YLb);e(d=_geo.c.ra.gf.filters.YLb.prototype,"getFrequencyBoundary",d.a7,{a7:0});
e(d,"setFrequencyBoundary",d.fZ,{fZ:0});e(d,"setPassFlag",d.bva,{bva:0});e(d,"getPassFlag",d.dca,{dca:0});e(d,"isApplicable",d.Ah,{Ah:0});e(d,"getState",d.Yl,{Yl:0});e(d,"setState",d.Un,{Un:0});e(d,"process",d.gl,{gl:0});g(b+"."+a+".analysis.filters.TaperFrequencyBoundary",f.qJa);e(d=_geo.c.ra.gf.filters.qJa.prototype,"setFrequencyBoundary",d.fZ,{fZ:0});e(d,"isValid",d.ge,{ge:0});e(d,"equals",d.lh,{lh:0});e(d,"getF1",d.Wra,{Wra:0});e(d,"setF1",d.Yab,{Yab:0});e(d,"getF2",d.Xra,{Xra:0});e(d,"setF2",
d.Zab,{Zab:0});e(d,"getF3",d.Yra,{Yra:0});e(d,"setF3",d.$ab,{$ab:0});e(d,"getF4",d.Zra,{Zra:0});e(d,"setF4",d.abb,{abb:0})})();

    return _geo.geotoolkit.seismic.analysis;
}(_geo));
/* eslint-enable */
/* tslint:enable */