/* tslint:disable */
/* eslint-disable */
/**
 * Copyright: Copyright (c) 2016 by INT, Inc.  All rights reserved.<br>
 * Company: INT, Inc. <br>
 * INT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
import {_geo} from './geotoolkit.adv.module.js';

export let svg = (function (_geo) {var _geo=_geo||{};_geo.c.dc=_geo.c.dc||{};_geo.c.dc.Gb=_geo.c.dc.Gb||{};_geo.c.dc.fS=function(){function b(){this.jd=this.eoa=null}_geo.c.ja(b,"geotoolkit.svg.ElementParser");b.prototype.wFa=_geo.c.Ua;b.prototype.Co=_geo.c.Ua;b.prototype.getName=function(){return this.jd};b.prototype.parse=_geo.c.Ua;return b}();
_geo.c.dc.lM=function(){function b(){_geo.c.dc.fS.call(this);this.OJc=null;this.Apc=_geo.c.f.pj.y7a();this.eoa=null}var a=1,g=2,e=2,d=4,f=new _geo.c.f.vb(0,0,0,0),h=20,l=.001;_geo.c.na(b,_geo.c.dc.fS);_geo.c.ja(b,"geotoolkit.svg.AbstractParser");b.prototype.Co=function(){return this.eoa};b.prototype.wFa=function(a){if(!(a instanceof _geo.c.dc.ena))throw Error("Invalid document parser passed");this.eoa=a};b.prototype.Fz=function(a,b,d,e){a=Math.atan2(a*e-b*d,a*d+b*e);return 0>a?2*Math.PI+a:a};b.prototype.getAttribute=
function(a,b){if(!a||!a.attributes)return"";var d=a.attributes.getNamedItem(b);return d?d.nodeValue:""};b.prototype.qO=function(a,b){if(!b)return null;var d=this.eoa.jyc()[a.nodeName],e=new _geo.c.dc.efa(d),d=b.ac().clone(),f=this.getAttribute(a,"class");if(this.Be(f))for(var f=f.split(" "),g=0;g<f.length;g++)e=e.Jy(this.eoa.ac("."+f[g]));f=this.getAttribute(a,"id");this.Be(f)&&(e=e.Jy(this.eoa.ac("#"+f)));f=this.getAttribute(a,"style");if(this.Be(f)){var f=this.eoa.U6().H$a(f),h;for(h in f)f.hasOwnProperty(h)&&
e.yg(h,f[h],null)}h="visibility fill fill-rule int:stroke-fixedwidth stroke-width stroke-linecap stroke-linejoin stroke-miterlimit stroke stroke-dasharray stroke-opacity fill-opacity".split(" ");var l=this;h.forEach(function(b){var d=l.getAttribute(a,b);l.Be(d)&&e.yg(b,d)});h=this.getAttribute(a,"opacity");if(this.Be(h))if(f=d.ac("opacity"),this.Be(f)){f=(0,window.parseFloat)(f);if((0,window.isNaN)(f)||1<f)f=1;h=(0,window.parseFloat)(h);(0,window.isNaN)(h)||(1<h&&(h=1),f*=h);e.yg("opacity",f)}else e.yg("opacity",
h);h=this.getAttribute(a,"text-anchor");this.Be(h)&&e.yg("text-anchor",h);h=this.getAttribute(a,"text-decoration");this.Be(h)&&e.yg("text-decoration",h);h=this.getAttribute(a,"font-family");var f=this.getAttribute(a,"font-style"),g=this.getAttribute(a,"font-size"),v=this.getAttribute(a,"font-weight"),w=this.getAttribute(a,"baseline-shift");this.Be(h)&&(h.startsWith("'")&&h.endsWith("'")&&(h=h.replace(/'/g,"")),e.yg("font-family",h));this.Be(f)&&e.yg("font-style",f);this.Be(v)&&e.yg("font-weight",
v);this.Be(g)&&e.yg("font-size",g);this.Be(w)&&e.yg("baseline-shift",w);return d.Jy(e)};b.prototype.zJ=function(a,b){if(null==this.Co())throw Error("Document parser was not found");if(!a||!b)throw Error("Invalid parameters");for(var d=b.Ub(),e=null,f=a.firstChild;null!==f;f=f.nextSibling)f.nodeType===_geo.c.window.Node.ELEMENT_NODE&&(e=this.Co().Ny(f,b),null!=e&&e!==d&&d instanceof _geo.c.V.Yj&&e instanceof _geo.c.V.Node&&d.Ia(e));return this};b.prototype.USa=function(a){var b=0,d=0,e,f,g=0,h=0,l=
0,v=0,w="",x=!1,y=Number.NEGATIVE_INFINITY,B=Number.NEGATIVE_INFINITY;a=new _geo.c.dc.IJb(a);for(var A=new _geo.c.V.$.Dk;"0"!==(w=a.mxb());){switch(w){case "Z":case "z":A.lineTo(l,v);A.close();b=l;d=v;continue;case "A":case "a":var C=this.Zt(a.yJ(),0),D=this.as(a.yJ(),0),E=this.as(a.yJ(),0)*(Math.PI/180),F=this.as(a.yJ(),0),J=this.as(a.yJ(),0);e=this.Zt(a.yJ(),0);f=this.as(a.yJ(),0);"a"===w&&(e+=b,f+=d);if(1E-7>C||1E-7>D){A.moveTo(e+C,f+D);A.lineTo(e,f);break}w=new _geo.c.dc.EJb(A);b=this.Lqb(C,D,
E,F,J,{x:e,y:f},{x:b,y:d});_geo.c.dc.gc.qC(w,b.nuc,b.ouc,2*C,2*D,b.Jcc,b.Jcc+b.Fuc,J,e,f);b=e;d=f;continue}C="V"===w||"v"===w?this.Zt(a.yJ(),0):this.as(a.yJ(),0);switch(w){case "h":A.lineTo(b=C+b,d);continue;case "H":A.lineTo(b=C,d);continue;case "v":A.lineTo(b,d=C+d);continue;case "V":A.lineTo(b,d=C);continue}D=this.as(a.yJ(),0);switch(w){case "m":if(x){l+=C;v+=D;b+=C;d+=D;A.moveTo(b,d);continue}l=C;v=D;b=C;d=D;h=C;g=D;A.moveTo(b,d);x=!0;continue;case "M":l=C;v=D;b=C;d=D;h=C;g=D;A.moveTo(b,d);x=
!0;continue;case "L":b=C;d=D;h=C;g=D;A.lineTo(b,d);continue;case "l":b+=C;d+=D;A.lineTo(b,d);continue;case "T":y===Number.NEGATIVE_INFINITY&&(y=b);B===Number.NEGATIVE_INFINITY&&(B=d);e=b+(b-y);f=d+(d-B);this.DEa(A,b,d,e,f,C,D);b=C;d=D;y=e;B=f;continue;case "t":y===Number.NEGATIVE_INFINITY&&(y=b);B===Number.NEGATIVE_INFINITY&&(B=d);e=b+(b-y);f=d+(d-B);this.DEa(A,b,d,b+(b-y),d+(d-B),b=C+b,d=D+d);y=e;B=f;continue}e=this.Zt(a.yJ(),0);f=this.as(a.yJ(),0);switch(w){case "S":!1===Number.isFinite(h)?A.bezierCurveTo(b,
d,C,D,b=e,d=f):A.bezierCurveTo(b+(b-h),d+(d-g),C,D,b=e,d=f);h=e;g=f;continue;case "s":!1===Number.isFinite(h)?A.bezierCurveTo(b,d,C+b,D+d,e+b,f+d):A.bezierCurveTo(b+(b-h),d+(d-g),C+b,D+d,e+b,f+d);h=C+b;g=D+d;b=e+b;d=f+d;continue;case "Q":this.DEa(A,b,d,C,D,b=e,d=f);y=C;B=D;continue;case "q":y=C+b;B=D+d;this.DEa(A,b,d,C+b,D+d,b=e+b,d=f+d);continue}J=this.Zt(a.yJ(),0);E=this.as(a.yJ(),0);switch(w){case "C":A.bezierCurveTo(C,D,e,f,b=J,d=E);h=e;g=f;continue;case "c":A.bezierCurveTo(C+b,D+d,e+b,f+d,J+
b,E+d);h=e+b;g=f+d;b=J+b;d=E+d;continue}}return A};b.prototype.Lqb=function(a,b,d,e,f,g,h){function l(a,b){return(a[0]*b[1]<a[1]*b[0]?-1:1)*Math.acos(v(a,b))}function v(a,b){return(a[0]*b[0]+a[1]*b[1])/(w(a)*w(b))}function w(a){return Math.sqrt(Math.pow(a[0],2)+Math.pow(a[1],2))}d*=Math.PI/180;var x=new _geo.c.f.sa(Math.cos(d)*(h.x-g.x)/2+Math.sin(d)*(h.y-g.y)/2,-Math.sin(d)*(h.x-g.x)/2+Math.cos(d)*(h.y-g.y)/2),y=Math.pow(x.x,2)/Math.pow(a,2)+Math.pow(x.y,2)/Math.pow(b,2);1<y&&(a*=Math.sqrt(y),b*=
Math.sqrt(y));e=(e===f?-1:1)*Math.sqrt((Math.pow(a,2)*Math.pow(b,2)-Math.pow(a,2)*Math.pow(x.y,2)-Math.pow(b,2)*Math.pow(x.x,2))/(Math.pow(a,2)*Math.pow(x.y,2)+Math.pow(b,2)*Math.pow(x.x,2)));(0,window.isNaN)(e)&&(e=0);e=new _geo.c.f.sa(e*a*x.y/b,e*-b*x.x/a);d=new _geo.c.f.sa((h.x+g.x)/2+Math.cos(d)*e.x-Math.sin(d)*e.y,(h.y+g.y)/2+Math.sin(d)*e.x+Math.cos(d)*e.y);g=l([1,0],[(x.x-e.x)/a,(x.y-e.y)/b]);h=[(x.x-e.x)/a,(x.y-e.y)/b];a=[(-x.x-e.x)/a,(-x.y-e.y)/b];b=l(h,a);-1>=v(h,a)&&(b=Math.PI);1<=v(h,
a)&&(b=0);return{nuc:d.x,ouc:d.y,Fuc:b,Jcc:g}};b.prototype.DEa=function(a,b,d,e,f,g,h){b={wwb:b,xwb:d,Pyb:0};this.$Ua(a,e,f,g,h,b)};b.prototype.$Ua=function(a,b,d,e,f,g){g.Pyb++;var r=this.IBa(b,d,g.wwb,g.xwb,e,f);if(r<=l||g.Pyb>=h)g.wwb=e,g.xwb=f,a.lineTo(e,f);else{var r=.5*(g.wwb+b),n=.5*(g.xwb+d);b=.5*(e+b);d=.5*(f+d);this.$Ua(a,r,n,.5*(r+b),.5*(n+d),g);this.$Ua(a,b,d,e,f,g)}g.Pyb--};b.prototype.IBa=function(a,b,d,e,f,g){var h=Math.sqrt((d-f)*(d-f)+(e-g)*(e-g)),l=0;0!==h&&(l=Math.abs((d-a)*(g-
b)-(e-b)*(f-a))/h);return l};b.prototype.Zt=function(b,d){return this.Vta(b,d,a)};b.prototype.as=function(b,d){return this.Vta(b,d,a)};b.prototype.RY=function(b,d){return this.Vta(b,d,a)};b.prototype.RU=function(a,b){return this.Vta(a,b,d)};b.prototype.Vta=function(a,b,d){if("string"!==typeof a||0===a.length)return b;var e=this.Co().U6();return null!==e?this.fra(e.h8(a),d):b};b.prototype.Uta=function(b){if(!b)return null;var d=this.Co().U6();if(null!==d){var e=d.h8(b);b=this.fra(e,a);e=e.Ria();e.sq()===
e.sq("CssOperatorComma")&&(e=e.Ria());d=this.fra(e,g);e=e.Ria();e.sq()===e.sq("CssOperatorComma")&&(e=e.Ria());var f=this.fra(e,a),e=e.Ria();e.sq()===e.sq("CssOperatorComma")&&(e=e.Ria());e=this.fra(e,a);return new _geo.c.f.Rect(b,d,b+f,d+e)}return null};b.prototype.fra=function(b,f){switch(b.sq()){case b.sq("CssInteger"):return b.yn();case b.sq("CssReal"):return b.yn();case b.sq("CssPercentage"):var h=this.Co().cvb(),l=b.yn()/100;switch(f){case a:return l*h.ba();case g:return l*h.da();case d:return l*
h.ba();case e:return l*h.da();default:return l*Math.sqrt(h.ba()*h.ba()+h.da()*h.da())/2}}return b.yn()*this.Co().Zb(b.ksb())};b.prototype.RSa=function(a,b){if(null==b||!this.Co().vYb()||!a)return null;var d=this.Co().Rra(a);if(null==d){d=this.p7("url",a);if(!d.$g())return null;d=d.KY();d=this.Co().Rra(d)}if(null==d)return null;d=this.Co().Ny(d,b);null!==b.ZE()&&(null!==d?d.zi(b.ZE()):d=b.ZE().clone());return d};b.prototype.uPc=function(a,b,d,e){return a};b.prototype.Be=function(a){return!!a};b.prototype.AJ=
function(a){if(!this.Be(a))return null;a=a.split(")");for(var b=new _geo.c.f.Fa,d=0;d<a.length;d++)if(this.Be(a[d])){var e=a[d]+")",f;if(null!==(f=this.p7("matrix",e)))for(var e=[],g=0;6>g;g++)e[g]=(0,window.parseFloat)(f.KY()),b=new _geo.c.f.Fa(e[0],e[1],e[2],e[3],e[4],e[5]);else null!==(f=this.p7("scale",e))?(e=this.rO(f.KY(),1),f=f.$g()?this.rO(f.KY(),e):e,b.scale(e,f)):null!==(f=this.p7("translate",e))?(e=(0,window.parseFloat)(f.KY()),f=f.$g()?this.rO(f.KY(),0):0,b.translate(e,f)):null!==(f=this.p7("rotate",
e))?(e=(0,window.parseFloat)(f.KY())*(Math.PI/180),g=f.$g()?this.rO(f.KY(),0):0,f=f.$g()?this.rO(f.KY(),0):0,b.translate(g,f),b.rotate(e),b.translate(-g,-f)):null!==(f=this.p7("skewX",e))?b.Q8(Math.tan((0,window.parseFloat)(f.KY())*(Math.PI/180)),0):null!==(f=this.p7("skewY",e))&&b.Q8(0,Math.tan((0,window.parseFloat)(f.KY())*(Math.PI/180)))}return b};b.prototype.rO=function(a,b){if(!this.Be(a))return b;var d=(0,window.parseFloat)(a);(0,window.isNaN)(d)&&(d=b);return d};b.prototype.p7=function(a,b){function d(a){this.Ph=
0;this.BEb=[];a=e.exec(a);if(null!=a[1]){a=a[1].split(/[ ,;\n\r\t]/);for(var b=0;b<a.length;b++)""!==a[b]&&this.BEb.push(a[b])}}var e=/\(([^)]+)\)/;if(-1===b.indexOf(a))return null;d.prototype.$g=function(){return this.Ph<this.BEb.length};d.prototype.KY=function(){return this.BEb[this.Ph++]||null};return new d(b)};b.prototype.rBa=function(a,b){return null!=a&&null!=b?(new _geo.c.f.Fa(b)).Gz(a):null!=a?a.clone():null!=b?b.clone():null};b.prototype.KQ=function(a,b){a instanceof _geo.c.dc.bv&&(b=a,a=
b.ac());if(!a)return null;var d=new _geo.c.attributes.za,e={linestyle:d};d.pUa(_geo.c.attributes.za.gK.a4);var g=this.Lpb(this.tU(a,"fill"),b);e.fillstyle=g||new _geo.c.attributes.Ha;null!==a.ac("stroke-width")||null!==a.ac("stroke-linecap")||null!==a.ac("stroke-linejoin")||null!==a.ac("stroke-miterlimit")?d.ed("black"):d.ed(f);g=this.tU(a,"int:stroke-fixedwidth");this.Be(g)||this.zbb(!0);g=this.tU(a,"stroke-width");g=this.RU(g,1);d.rb(g);g=this.Mpb(this.tU(a,"stroke-linecap"));null!==g&&d.Hua(g);
g=this.Npb(this.tU(a,"stroke-linejoin"));null!==g&&d.pUa(g);g=this.tU(a,"stroke-dasharray");if(this.Be(g)&&"none"!==g){for(var g=g.split(/[ ,;\n\r\t]/),h=[],l=0;l<g.length;l++){var n=g[l];""!==n[l]&&h.push((0,window.parseFloat)(n))}this.zbb(d,!0);d.wH(h)}h=this.tU(a,"stroke");this.Be(h)&&"none"!==h?d.ed(new _geo.c.f.vb(h)):d.ed(f);g=this.tU(a,"fill-opacity");this.Be(g)&&this.ebb(e.fillstyle,g);g=this.tU(a,"opacity");this.Be(g)&&(this.ebb(e.fillstyle,g),"none"!==h&&this.Nbb(d,g));g=this.tU(a,"stroke-opacity");
this.Be(g)&&"none"!==h&&this.Nbb(d,g);g=this.tU(a,"display");this.Be(g)&&(e.visible="none"!==g);return e};b.prototype.zbb=function(a,b){return this};b.prototype.Z6a=function(a,b){0>b&&(b=0);1<b&&(b=1);a=_geo.c.f.vb.gb(a);a.EJ(a.Ip()*b);return a=a.Dr()};b.prototype.ebb=function(a,b){var d=(0,window.parseFloat)(b),e;if(a instanceof _geo.c.attributes.Dj)for(var f=a.kJ(),g=0;g<f;g++)e=a.XN(g),a.KCb(g,this.Z6a(e,d));else a instanceof _geo.c.attributes.Ha&&(e=a.Kc(),a.ed(this.Z6a(e,d)));return this};b.prototype.Nbb=
function(a,b){var d=(0,window.parseFloat)(b),e=a.Kc();0>d&&(d=0);1<d&&(d=1);if("string"===typeof e)var f=this.Apc[e],e=f?f.clone():_geo.c.f.pj.Nha(e);e instanceof _geo.c.f.vb&&e.ed(e.Mp(),e.Lp(),e.Jp(),255*d);a.ed(e);return this};b.prototype.Mpb=function(a){return this.Be(a)?"butt"===a?_geo.c.attributes.za.GF.l9:"round"===a?_geo.c.attributes.za.GF.vj:"square"===a?_geo.c.attributes.za.GF.yxa:null:null};b.prototype.Npb=function(a){return this.Be(a)?"miter"===a?_geo.c.attributes.za.gK.a4:"bevel"===a?
_geo.c.attributes.za.gK.lWa:"round"===a?_geo.c.attributes.za.gK.vj:null:null};b.prototype.C$a=function(a,b){return this.Vta(a,b,d)};b.prototype.tU=function(a,b){return a.ac(b)};b.prototype.Lpb=function(a,b){if(!this.Be(a))return new _geo.c.attributes.Ha("black");var d=this.p7("url",a),e=_geo.c.attributes.Ha.ag;if(null===d)return e=new _geo.c.attributes.Ha,d="none"===a?f:new _geo.c.f.vb(a),e.ed(d),e;d=d.KY();if(null===d)return e;d=this.Co().Rra(d);if(null!=d)switch(d.nodeName){case "linearGradient":e=
this.Opb(d,b);break;case "radialGradient":e=this.Qpb(d,b);break;case "pattern":e=this.Ppb(d,b);break;default:e=null;break}return e};b.prototype.Opb=function(a,b){if("linearGradient"!==a.nodeName)return null;for(var d=[],e=a,g="",h="",l="",n="",v="",w="",x="";null!=e;)g=g||this.getAttribute(e,"gradientTransform"),h=h||this.getAttribute(e,"gradientUnits"),l=l||this.getAttribute(e,"spreadMethod"),n=n||this.getAttribute(e,"x1"),v=v||this.getAttribute(e,"x2"),w=w||this.getAttribute(e,"y1"),x=x||this.getAttribute(e,
"y2"),0===d.length&&this.yWb(e,d),e=this.Co().Rra(this.getAttribute(e,"xlink:href"));(e="userSpaceOnUse"===h)?(n=this.Zt(n,0),w=this.as(w,0),v=this.Zt(v,0),x=this.as(x,0)):(n=this.s2(n,0),w=this.s2(w,0),v=this.s2(v,1),x=this.s2(x,0));if(n===v&&w===x)return new _geo.c.attributes.Ha(0<d.length?d[d.length-1].color:f);w=new _geo.c.f.sa(n,w);x=new _geo.c.f.sa(v,x);l=new _geo.c.attributes.wt(d[0].color,d[d.length-1].color,w,x,null,l,!0===e?"userSpaceOnUse":"objectBoundingBox");g=this.AJ(g);null!==g&&l.sc(g);
for(g=0;g<d.length;g++)l.Bo(d[g].offset,d[g].color);d=new _geo.c.dc.bv(null,b.$a(),new _geo.c.dc.efa,null,null,l,b.tD());this.zJ(a,d);return l};b.prototype.Qpb=function(a,b){if("radialGradient"!==a.nodeName)return null;for(var d=a,e="",f="",g="",h="",l="",v="",w="",x="",y=[];null!=d;)e=e||this.getAttribute(d,"gradientTransform"),g=g||this.getAttribute(d,"gradientUnits"),f=f||this.getAttribute(d,"spreadMethod"),h=h||this.getAttribute(d,"cx"),l=l||this.getAttribute(d,"cy"),v=v||this.getAttribute(d,
"r"),w=w||this.getAttribute(d,"fx"),x=x||this.getAttribute(d,"fy"),0===y.length&&this.yWb(d,y),d=this.Co().Rra(this.getAttribute(d,"xlink:href"));var d="userSpaceOnUse"===g,B=0,A=0,C=g=0;if(d)var D=this.Co().cvb(),B=this.Be(h)?this.Zt(h,B):D.Xh().ga(),A=this.Be(l)?this.as(l,A):D.Xh().ea(),h=this.Be(v)?this.Zt(v,100):.5*D.da(),g=this.Be(w)?this.Zt(w,g):B,C=this.Be(x)?this.as(x,C):A;else B=this.s2(h,.5),A=this.s2(l,.5),h=this.s2(v,.5),g=this.s2(w,B),C=this.s2(x,A);w=new _geo.c.f.sa(B,A);x=new _geo.c.f.sa(g,
C);y.sort(function(a,b){return a.offset-b.offset});f=new _geo.c.attributes.p_({startcolor:y[0].color,endcolor:y[y.length-1].color,innercenter:x,innerradius:0,outercenter:w,outerradius:h,spreadmethod:f,unittype:!0===d?"userSpaceOnUse":"objectBoundingBox"});e=this.AJ(e);null!==e&&f.sc(e);for(e=1;e<y.length-1;e++)f.Bo(y[e].offset,y[e].color);y=new _geo.c.dc.bv(null,b.$a(),new _geo.c.dc.efa,null,null,f,b.tD());this.zJ(a,y);return f};b.prototype.yWb=function(a,b){for(var d=0;d<a.childNodes.length;d++){var e=
a.childNodes.item(d);if(null!=e&&e.nodeType===_geo.c.window.Node.ELEMENT_NODE&&"stop"===e.nodeName){var f=this.getAttribute(e,"offset"),g=this.Co().U6().h8(f),f=g.yn();g.sq()===g.sq("CssPercentage")&&(f/=100);f=Math.max(0,Math.min(f,1));g=this.getAttribute(e,"style");this.Be(g)?(e=this.Co().U6().H$a(g),g=e["stop-color"],e=e["stop-opacity"]):(g=this.getAttribute(e,"stop-color"),e=this.getAttribute(e,"stop-opacity"));var h="none"===g?new _geo.c.f.vb(0,0,0,1):new _geo.c.f.vb(g),g=h.Mp(),l=h.Lp(),v=h.Jp(),
h=h.Ip()/255;this.Be(e)&&(e=this.Co().U6().h8(e),h=e.yn());e="rgba("+[g,l,v,h].join()+")";b.push({offset:f,color:e})}}};b.prototype.s2=function(a,b){if(!this.Be(a))return b;var d=this.Co().U6().h8(a);return d.sq()===d.sq("CssPercentage")?d.yn()/100:d.yn()};b.prototype.Ppb=function(a,b){for(var d="",e="",f="",g="",h="",l="",v="",w="",x="",y="",B=a;null!=a;)0===d.length&&(d=this.getAttribute(a,"x")),0===e.length&&(e=this.getAttribute(a,"y")),0===f.length&&(f=this.getAttribute(a,"height")),0===g.length&&
(g=this.getAttribute(a,"width")),0===h.length&&(h=this.getAttribute(a,"viewBox")),0===l.length&&(l=this.getAttribute(a,"patternUnits")),0===v.length&&(v=this.getAttribute(a,"patternContentUnits")),0===w.length&&(w=this.getAttribute(a,"patternTransform")),0===x.length&&(x=this.getAttribute(a,"preserveAspectRatio")),0===y.length&&(y=this.getAttribute(a,"clip-path")),0<a.childNodes.length&&0===B.childNodes.length&&(B=a),a=this.Co().Rra(this.getAttribute(a,"xlink:href"));var l="userSpaceOnUse"===l,A,
C;l?(x=this.Zt(d,0),y=this.as(e,0),A=this.RY(f,100),C=this.RU(g,100)):(C=b.Ub().ha(),x=C.ga()+C.ba()*this.Zt(d,0),y=C.ea()+C.da()*this.as(d,0),A=C.da()*this.RY(f,100),C=C.ba()*this.RU(g,100));x=new _geo.c.f.Rect(x,y,x+C,y+A);h=this.Uta(h);A=this.AJ(w)||new _geo.c.f.Fa;w=new _geo.c.attributes.Ha;y=new _geo.c.V.Ya;y.Ea(new _geo.c.attributes.Ha("white"));A=new _geo.c.dc.bv([],A,new _geo.c.dc.efa,null,null,y,b.tD());this.zJ(B,A);v="userSpaceOnUse"===v;null!=h?y.cb(h):v||l?y.cb(x):y.cb(new _geo.c.f.Rect(this.Zt(d,
0),this.as(e,0),this.RU(g,100),this.RY(f,100)));y.Ga(x);return 0<A.Zq().length?(d=new _geo.c.attributes.zea({model:y,scalable:this.Co().zzb()}),w.wH(d),w):null};b.prototype.e9a=function(a){var b=null,b=null!==a.va()&&void 0!==a.va()?new _geo.c.Sa.canvas.Fr(a.va().ba(),a.va().da()):new _geo.c.Sa.canvas.Fr(64,64),d=b.mq(new _geo.c.f.Fa,new _geo.c.f.sa(0,0));null!=d&&d.filter(a)&&a.Aa(d);b.Hp();return b.Lk().toDataURL()};b.prototype.kt=function(a,b){if(null==a)return b;var d=12,e=a.ac().ac("font-family"),
f=a.ac().ac("font-style"),g=a.ac().ac("font-size"),h=a.ac().ac("font-weight");if(null==e&&null==f&&null==g&&null==h)return b;this.Be(e)||(e="Arial");this.Be(f)&&"normal"!==f||(f="");this.Be(h)||(h="normal");if(this.Be(g))d=Number(g),Number.isNaN(d)&&(d=g);else switch(g){case "xx-small":d/=1.728;break;case "x-small":d/=1.44;break;case "small":d/=1.2;break;case "xx-large":d*=1.728;break;case "x-large":d*=1.44;break;case "large":d*=1.2;break;default:d=this.C$a(g,d)}Number(d)===d&&(d+="px");return(b||
new _geo.c.attributes.kb).ka({font:(f+" "+h+" "+d+" "+e).trim()})};return b}();
_geo.c.dc.IJb=function(){function b(a){this.kQ=a;this.yp=0;this.mya=-1}var a="ZzMmLlHhVvSsCcQqTtAa",g="0123456789.eE",e=", \t\n\r";_geo.c.ja(b,"geotoolkit.svg.PathTokenizer");b.prototype.mxb=function(){if(-1!==this.mya){var b=this.yp,e=this.yJ();if(""!==e&&null!==e)return this.yp=b,"M"===a[this.mya]?a[4]:"m"===a[this.mya]?a[5]:a[this.mya]}if(this.yp>=this.kQ.length)return"0";for(;-1===(this.mya=a.indexOf(this.kQ[this.yp]));)if(this.yp++,this.yp>=this.kQ.length)return"0";this.yp++;return a[this.mya]};
b.prototype.yJ=function(){if(this.yp>=this.kQ.length)return"";for(;-1!==e.indexOf(this.kQ[this.yp]);)if(this.yp++,this.yp>=this.kQ.length)return null;var a=this.yp;for("-"===this.kQ[this.yp]&&this.yp++;(-1!==g.indexOf(this.kQ[this.yp])||("+"===this.kQ[this.yp]||"-"===this.kQ[this.yp])&&0<this.yp&&("e"===this.kQ[this.yp-1]||"E"===this.kQ[this.yp-1]))&&!(this.yp++,this.yp>=this.kQ.length););return this.kQ.substring(a,this.yp)};return b}();
_geo.c.dc.efa=function(){function b(a){this.fi={};this.rI={};if(a){for(var b in a.fi)a.fi.hasOwnProperty(b)&&(this.fi[b]=a.fi[b]);for(b in a.rI)a.rI.hasOwnProperty(b)&&(this.rI[b]=a.rI[b].clone())}this.jd=""}_geo.c.ja(b,"geotoolkit.svg.SvgStyle");b.prototype.Qb=function(a){this.jd=a||"";return this};b.prototype.toString=function(){var a="",b;for(b in this.fi)this.fi.hasOwnProperty(b)&&(a+=b,a+=":",a+=this.fi[b],a+=";");return a};b.prototype.yg=function(a,b,e){if(null==a&&null==e)return null;null!=
e?this.rI.hasOwnProperty(e)?this.rI[e].Jy(b):this.rI[e]=b:this.fi[a]=b;return this};b.prototype.ac=function(a,b){return b?this.rI.hasOwnProperty(a)?this.rI[a]:null:this.fi.hasOwnProperty(a)?this.fi[a]:null};b.prototype.Jy=function(a){if(null===a||void 0===a||null===a.fi)return this;for(var b in a.fi)a.fi.hasOwnProperty(b)&&(this.fi[b]=a.fi[b]);for(b in a.rI)a.rI.hasOwnProperty(b)&&(null==this.rI[b]||void 0===this.rI[b]?this.rI[b]=a.rI[b]:this.rI[b].Jy(a.rI[b]));return this};b.prototype.clone=function(){return new _geo.c.dc.efa(this)};
return b}();
_geo.c.dc.ena=function(){function b(a,b){var e=_geo.c.Ja(a,{xmldocument:"string"==typeof a?this.tEa(a):a,dpi:null!=b?b:96});this.Qza=e.xmldocument||null;this.DKa=e.dpi;this.Cmc=new _geo.c.Uf.Lx;this.rRb=this.jNb=!0;this.sSb=this.MSb=null;this.UK={};this.fi={};this.$Nb={};this.qRb=!0;this.qSb=!1;this.rmc=.3937;this.coc=.03937;this.Ik={px:1,cm:this.rmc*this.DKa,mm:this.coc*this.DKa,pt:.0139*this.DKa,pc:.167*this.DKa,"in":this.DKa,em:1,ex:1};this.pC(new _geo.c.dc.Gb.uKb);this.pC(new _geo.c.dc.Gb.yZa);this.pC(new _geo.c.dc.Gb.UFb);
this.pC(new _geo.c.dc.Gb.dKb);this.pC(new _geo.c.dc.Gb.Yu);this.pC(new _geo.c.dc.Gb.BGb);this.pC(new _geo.c.dc.Gb.VGb);this.pC(new _geo.c.dc.Gb.GXa);this.pC(new _geo.c.dc.Gb.HLb);this.pC(new _geo.c.dc.Gb.eKb);this.pC(new _geo.c.dc.Gb.IMb);this.pC(new _geo.c.dc.Gb.HJb);this.pC(new _geo.c.dc.Gb.xIb);this.pC(new _geo.c.dc.Gb.QEb);this.pC(new _geo.c.dc.Gb.dlc);this.pC(new _geo.c.dc.Gb.n4);this.pC(new _geo.c.dc.Gb.VFb);this.pC(new _geo.c.dc.Gb.XVa);this.pC(new _geo.c.dc.Gb.eFb);this.pC(new _geo.c.dc.Gb.cFb);
this.pC(new _geo.c.dc.Gb.dFb)}_geo.c.ja(b,"geotoolkit.svg.SVGParser");b.prototype.Zb=function(a){return this.Ik.hasOwnProperty(a)?this.Ik[a]:1};b.prototype.hTb=function(a,b){this.$Nb[a]=b;return this};b.prototype.Rra=function(a){return this.$Nb[a]||null};b.prototype.il=function(a,b){this.Ik[a]=b;return this};b.prototype.qGc=function(a){this.sSb=a;return this};b.prototype.cvb=function(){return this.sSb};b.prototype.occ=function(a){this.MSb=a;return this};b.prototype.EMc=function(){return this.MSb};
b.prototype.jyc=function(){return this.fi};b.prototype.ac=function(a){return this.fi[a]||null};b.prototype.yg=function(a,b){null==b&&(b="*");this.fi.hasOwnProperty(b)?this.fi[b].Jy(a):this.fi[b]=a;return this};b.prototype.U6=function(){return this.Cmc};b.prototype.tEa=function(a){if(null==a||""===a)throw Error("Invalid XML Document");var b=new _geo.c.window.DOMParser;a=b.parseFromString(a,"image/svg+xml");if("parsererror"===a.documentElement.nodeName||0<a.getElementsByTagName("parsererror").length)throw Error("Error while parsing SVG, invalid syntax");
return a};b.prototype.pC=function(a){if(null==a||null==a.getName())throw Error("Invalid or null parameter passed");a.wFa(this);this.UK[a.getName()]=a;return this};b.prototype.rFc=function(a){this.jNb=a;return this};b.prototype.vYb=function(){return this.jNb};b.prototype.ROc=function(a){return this};b.prototype.cMc=function(){return null};b.prototype.VOc=function(a){this.rRb=a;return this};b.prototype.vMc=function(){return this.rRb};b.prototype.zzb=function(){return this.qRb};b.prototype.sbc=function(a){this.qRb=
a;return this};b.prototype.parse=function(a,b){null==b?b=this.Qza:"string"==typeof b&&(b=this.tEa(b));if(null==b)return null;for(var e=0;e<b.childNodes.length;e++){var d=b.childNodes[e];d.nodeType===d.PROCESSING_INSTRUCTION_NODE&&"xml-stylesheet"===d.target&&_geo.c.log("External stylesheets are not supported")}e=b.documentElement||b;e.normalize();for(var d=new _geo.c.dc.efa,f=[],h=a.fk();h.$g();)f.push(h.next());d=new _geo.c.dc.bv(f,null,d,null,null,a);a.je(new _geo.c.f.Fa);d.pCb(a);e=this.Ny(e,d);
return null!==e?{eb:e,IPc:this.cvb()}:null};b.prototype.Ny=function(a,b){if(null==a)return null;if(!(a instanceof _geo.c.window.SVGElement||this.qSb))if("svg"===a.localName)this.qSb=!0;else return null;var e=null;this.UK.hasOwnProperty(a.localName)&&(e=this.UK[a.localName].parse(a,b));var d=_geo.c.dc.lM.prototype.getAttribute.call(null,a,"id");null!=d&&""!==d&&this.hTb("#"+d,a);return e};b.prototype.T2b=function(a){null==a?a=this.Qza:"string"==typeof a&&(a=this.tEa(a));a=a.documentElement;return"svg"===
a.nodeName?this.UK[a.nodeName].Ntb(a):{}};return b}();
_geo.c.dc.bv=function(){function b(a,b,e,d,f,h,l,k){this.jAa=l||null;this.Vh=a||[];this.$c=b||null;this.Di=e||null;this.KM=d||null;this.MNb=f||null;this.sI=h||null;this.jKc=k}_geo.c.ja(b,"geotoolkit.svg.ParserContext");b.prototype.pCb=function(a){if(!(a instanceof _geo.c.V.Ya))return null;this.jAa=a;return this};b.prototype.tD=function(){return this.jAa};b.prototype.$a=function(){return this.$c};b.prototype.sc=function(a){this.$c=a;return this};b.prototype.Zq=function(){return this.Vh};b.prototype.ac=
function(){return this.Di};b.prototype.yg=function(a){this.Di=a;return this};b.prototype.RI=function(){return this.KM};b.prototype.S9b=function(a){this.KM=a;return this};b.prototype.ZE=function(){return this.MNb};b.prototype.Qab=function(a){this.MNb=a;return this};b.prototype.Ub=function(){return this.sI};b.prototype.RAa=function(a){this.Vh.push(a);return this};b.prototype.xyb=function(a,b){return new _geo.c.dc.bv(b||[],this.$a(),this.ac(),this.RI(),this.ZE(),a,this.tD(),this)};b.prototype.jTa=function(a){return null==
a?this:new _geo.c.dc.bv(this.Zq(),this.$a(),a,this.RI(),this.ZE(),this.Ub(),this.tD(),this)};return b}();
_geo.c.dc.fz=function(){function b(){_geo.c.dc.lM.call(this)}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.ShapeParser");b.prototype.N0=function(a,b,e){if(null==a||null==b||null==e)return a;this.Tnb(a,b,e);var d=e.ac().ac("visibility"),d=!(this.Be(d)&&"hidden"===d);a.Ma(d);e.Zq().push(a);this.Owb(a,b,e);b=this.getAttribute(b,"id");a.Ae(this.Be(b)?b:null);return a};b.prototype.Tnb=function(a,b,e){a&&this.Co().vYb()&&(b=this.getAttribute(b,"clip-path"),this.Be(b)&&(e=this.RSa(b,e))&&a.Py(new _geo.c.attributes.yC(e)))};
b.prototype.Owb=function(a,b,e){void 0!==a.dg&&a.dg();void 0!==a.Yg&&a.Yg()};return b}();_geo.c.dc.EJb=function(){function b(a){this.gh=a||new _geo.c.V.$.Dk}b.prototype.beginPath=function(){};b.prototype.bezierCurveTo=function(a,b,e,d,f,h){this.gh.bezierCurveTo(a,b,e,d,f,h);return this};b.prototype.moveTo=function(a,b){this.gh.moveTo(a,b);return this};b.prototype.F1b=function(){return this.gh};b.prototype.closePath=function(){};return b}();
_geo.c.dc.gc=function(){function b(){}b.qC=function(a,b,e,d,f,h,l,k,m,q){b=1===k?_geo.c.Sa.gc.tia(b,e,d,f,h,l):_geo.c.Sa.gc.tia(b,e,d,f,l,h);if(!(1>b.length))if(1===k)for(e=0;e<b.length;++e)k=b[e],a.bezierCurveTo(k.zZ,k.DZ,k.p3,k.r3,k.AZ,k.EZ);else for(e=b.length-1;0<=e;e--)k=b[e],0===e?(d=m,f=q):(d=b[e-1].AZ,f=b[e-1].EZ),a.bezierCurveTo(k.p3,k.r3,k.zZ,k.DZ,d,f)};return b}();
_geo.c.dc.JLb=function(){function b(){}_geo.c.ja(b,"geotoolkit.svg.SvgDataProvider");b.prototype.Q5b=function(a,b){if(null!==a&&void 0!==a&&""!==a&&"function"===typeof b){var e=new _geo.c.window.XMLHttpRequest;e.onreadystatechange=function(a){4===e.readyState&&(200===e.status?b(null,e.responseText):b(e.statusText))};e.open("GET",a);e.send()}};return b}();
_geo.c.dc.blc=function(){function b(a){this.jAa=new _geo.c.V.Ya;a=new _geo.c.dc.ena(a);a.parse(this.jAa)}_geo.c.ja(b,"geotoolkit.svg.SvgPainter");b.prototype.Aa=function(a,b){this.jAa.Ga(b);this.jAa.Aa(a)};return b}();
_geo.c.dc.X9=function(){function b(a){_geo.c.V.Ya.call(this,a);this.U3a=function(a){this.T0()}.bind(this)}_geo.c.na(b,_geo.c.V.Ya);_geo.c.ja(b,"geotoolkit.svg.SvgGroup");b.prototype.Ia=function(a){_geo.c.V.Ya.prototype.Ia.call(this,a);this.Scc(a);this.T0();return this};b.prototype.bh=function(a,b){_geo.c.V.Ya.prototype.bh.call(this,a,b);this.Scc(b);this.T0();return this};b.prototype.removeChild=function(a){_geo.c.V.Ya.prototype.removeChild.call(this,a);this.Idc(a);this.T0();return this};b.prototype.Scc=
function(a){a=a instanceof _geo.c.f.Iterator?a:_geo.c.f.Iterator.Hm(Array.isArray(a)?a:[a]);a.forEach(function(a){a.tb(_geo.c.V.Node.aa.pM,this.U3a);a.tb(_geo.c.V.Node.aa.jK,this.U3a)}.bind(this));return this};b.prototype.Idc=function(a){a=a instanceof _geo.c.f.Iterator?a:_geo.c.f.Iterator.Hm(Array.isArray(a)?a:[a]);a.forEach(function(a){a.pb(_geo.c.V.Node.aa.pM,this.U3a);a.pb(_geo.c.V.Node.aa.jK,this.U3a)}.bind(this));return this};b.prototype.Qa=function(a,b){if(this.HRb)return this;this.HRb=!0;
this.T0();_geo.c.V.Ya.prototype.Qa.call(this,a,b);this.HRb=!1;return this};b.prototype.Gh=function(a){for(var b=this.children.length-1;0<=b;--b)this.Idc(this.children[b]);_geo.c.V.Ya.prototype.Gh.call(this,a);this.T0();return this};b.prototype.T0=function(){for(var a=null,b=null,e=0;e<this.children.length;e++)if(this.children[e].ha&&(b=this.children[e].ha(),null!=b))var d=this.children[e].kc(),a=null!=d?null==a?d.yb(b):a.zi(d.yb(b)):null==a?b.clone():a.zi(b);this.Ga(null===a?new _geo.c.f.Rect:a)};
return b}();
_geo.c.dc.Gb.uKb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="rect"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.RectParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.Zt(this.getAttribute(a,"x"),0),d=this.as(this.getAttribute(a,"y"),0),f=this.RU(this.getAttribute(a,"width"),100),h=this.RY(this.getAttribute(a,"height"),100),l=this.Zt(this.getAttribute(a,"rx"),0),k=this.as(this.getAttribute(a,
"ry"),0),m=this.getAttribute(a,"id"),q=this.getAttribute(a,"class"),p=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa;0===l&&0!==k?l=k:0===k&&0!==l&&(k=l);l>f/2&&0!==l&&(l=f/2);k>h/2&&0!==k&&(k=h/2);e=(new _geo.c.V.$.Th({left:e,top:d,width:f,height:h})).Ae(this.Be(m)?m:null).Qb(this.jd).To(this.jd).pe(this.Be(q)?q:null).je(p);e.rH(l||k);l=this.qO(a,b);l=new _geo.c.dc.bv(b.Zq(),new _geo.c.f.Fa,l,e,b.ZE(),e,b.tD());k=this.KQ(l);e.ka(k);this.zJ(a,l);return this.N0(e,a,l)};return b}();
_geo.c.dc.Gb.yZa=function(){function b(){_geo.c.dc.fz.call(this);this.jd="svg"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.SvgParser");b.prototype.Ntb=function(a){var b=this.getAttribute(a,"overflow"),e=this.Uta(this.getAttribute(a,"viewBox")),d=this.RY(this.getAttribute(a,"height"),100);a=this.RU(this.getAttribute(a,"width"),100);return{overflow:b,viewBox:e,height:d,width:a}};b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");
var e=this.getAttribute(a,"overflow");"visible"===e&&this.Co().rFc(!1);var d=null,f=this.getAttribute(a,"viewBox");null!==f&&(d=this.Uta(f),this.Co().qGc(null!=d?d.clone():null));f=new _geo.c.f.Fa;if(null===b.$a())b.sc(new _geo.c.f.Fa);else{var h=this.Zt(this.getAttribute(a,"x"),0),l=this.as(this.getAttribute(a,"y"),0);if(0!==h||0!==l)f=_geo.c.f.Fa.Mj(h,l)}var h=null,k=this.getAttribute(a,"width"),l=null;null!=k&&""!==k&&(l=this.RU(k,null));var k=this.getAttribute(a,"height"),m=null;null!=k&&""!==
k&&(m=this.RY(k,null));null!=l&&null!=m&&(h=new _geo.c.f.Rect(0,0,l,m));k=b.Ub();l=null;l=null==k||k instanceof _geo.c.dc.X9?(new _geo.c.V.Ya).Qb("svg_root_group"):b.Ub();k=[];for(m=l.fk();m.$g();)k.push(m.next());var k=b.xyb(l,k),q=this.getAttribute(a,"clip-path"),m=null;null!=q&&""!==q&&(m=this.RSa(q,k),k.Qab(m));q=this.qO(a,k);null!=q&&(k=k.jTa(q));this.zJ(a,k);null!=d&&this.getAttribute(a,"preserveAspectRatio");l.je(f);null!=h&&l.Gf("visible"!==e).Ga(h);null==d?(this.Co().occ(null),l.Ed(!0)):
(this.Co().occ(d),l.cb(d));null!=m&&l.Py(new _geo.c.attributes.yC(m));return l};b.prototype.GUb=function(a,b,e,d){return new _geo.c.f.Fa};return b}();
_geo.c.dc.Gb.UFb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="circle"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.CircleParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.Zt(this.getAttribute(a,"cx"),0),d=this.as(this.getAttribute(a,"cy"),0),f=this.C$a(this.getAttribute(a,"r"),0),h=this.getAttribute(a,"id"),l=this.getAttribute(a,"class"),k=this.AJ(this.getAttribute(a,"transform"))||
new _geo.c.f.Fa,e=(new _geo.c.V.$.KF(e,d,f,f)).Ae(this.Be(h)?h:null).Qb(this.jd).To(this.jd).pe(this.Be(l)?l:null).je(k),k=this.rBa(k,b.$a()),d=this.qO(a,b),k=new _geo.c.dc.bv(b.Zq(),k,d,e,b.ZE(),e,b.tD()),d=this.KQ(k);e.ka(d);this.zJ(a,k);return this.N0(e,a,k)};return b}();
_geo.c.dc.Gb.dKb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="polygon"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.PolygonParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"points"),e=e.split(/[ ,;\n\r\t]/),d=[],f;for(f=0;f<e.length;f++)""!==e[f]&&d.push(e[f]);var e=[],h=[];for(f=0;f<d.length;f++){var l=this.Zt(d[f++],0),k=this.as(d[f],0);e.push(l);h.push(k)}f=
this.getAttribute(a,"id");l=this.getAttribute(a,"class");d=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa;e=(new _geo.c.V.$.If({x:e,y:h})).Ae(this.Be(f)?f:null).Qb(this.jd).To(this.jd).pe(this.Be(l)?l:null).je(d);h=this.qO(a,b);h=new _geo.c.dc.bv(b.Zq(),d,h,e,b.ZE(),e,b.tD());d=this.KQ(h);e.ka(d);this.zJ(a,h);return this.N0(e,a,h)};return b}();
_geo.c.dc.Gb.Yu=function(){function b(){_geo.c.dc.fz.call(this);this.jd="g"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.GroupParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"id"),d=this.getAttribute(a,"class"),f=this.qO(a,b),e=(new _geo.c.dc.X9).Ae(this.Be(e)?e:null).Qb(this.jd).To(this.jd).pe(this.Be(d)?d:null),d=this.getAttribute(a,"transform"),h=null;null!=d&&""!==
d&&(h=this.AJ(d),e.je(h));d=this.getAttribute(a,"viewBox");null!=d&&""!==d&&(d=this.Uta(d),e.cb(d));f=new _geo.c.dc.bv([],new _geo.c.f.Fa,f,e,b.ZE(),e,b.tD());d=this.getAttribute(a,"clip-path");null!=d&&(d=this.RSa(d,f))&&e.Py(new _geo.c.attributes.yC(d));f.Qab(null);this.zJ(a,f);return e};return b}();
_geo.c.dc.Gb.BGb=function(){function b(){_geo.c.dc.lM.call(this);this.jd="defs"}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.parsers.DefsParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");for(var e=null,d=a.firstChild;null!==d;d=d.nextSibling)d.nodeType===_geo.c.window.Node.ELEMENT_NODE&&("style"===d.nodeName?this.Co().Ny(d,b):(e=this.getAttribute(d,"id"),null!=e&&this.Co().hTb("#"+e,d)));return null};return b}();
_geo.c.dc.Gb.VGb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="ellipse"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.EllipseParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.Zt(this.getAttribute(a,"cx"),0),d=this.as(this.getAttribute(a,"cy"),0),f=this.RU(this.getAttribute(a,"rx"),0),h=this.RY(this.getAttribute(a,"ry"),0),l=this.getAttribute(a,"id"),k=this.getAttribute(a,"class"),
m=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa,e=new _geo.c.V.$.KF(e,d,f,h);e.Ae(this.Be(l)?l:null);e.Qb(this.jd);e.To(this.jd);e.pe(this.Be(k)?k:null);e.je(m);l=this.qO(a,b);m=new _geo.c.dc.bv(b.Zq(),m,l,e,b.ZE(),e,b.tD());l=this.KQ(m);e.ka(l);this.zJ(a,m);return this.N0(e,a,m)};return b}();
_geo.c.dc.Gb.GXa=function(){function b(){_geo.c.dc.fz.call(this);this.jd="image"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.ImageParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"xlink:href");if(!this.Be(e))return null;if(-1===e.indexOf("data:"))throw Error("External images are not yet supported");var d=this.Zt(this.getAttribute(a,"x"),0),f=this.as(this.getAttribute(a,
"y"),0),h=this.RU(this.getAttribute(a,"width"),100),l=this.RY(this.getAttribute(a,"height"),100),k=this.getAttribute(a,"id"),m=this.getAttribute(a,"class"),q=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa,p=(new _geo.c.V.$.Image({x:d,y:f,w:h,h:l,url:e})).Ae(this.Be(k)?k:null).Qb(this.jd).To(this.jd).pe(this.Be(m)?m:null).je(q),e=this.qO(a,b),q=new _geo.c.dc.bv(b.Zq(),q,e,p,b.ZE(),p,b.tD()),e=this.KQ(q);p.ka(e);p.tb(_geo.c.V.$.Image.aa.Hr,function(){p.ma()});this.zJ(a,q);b.tD().To("isResourceBased");
return this.N0(p,a,q)};return b}();
_geo.c.dc.Gb.HLb=function(){function b(){_geo.c.dc.lM.call(this);this.jd="style"}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.parsers.StyleParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");for(var e=0;e<a.childNodes.length;e++){var d=a.childNodes.item(e),f=null;if(d.nodeType===_geo.c.window.Node.CDATA_SECTION_NODE||d.nodeType===_geo.c.window.Node.TEXT_NODE)f=d.data;if(this.Be(f))for(d=_geo.c.Uf.Lx.parse(f),
0<d.Ms.uEa.length&&(_geo.c.log("Error occurred during CSS parsing"),_geo.c.log(d.Ms.uEa)),f=0;f<d.Ms.rules.length;f++)if("comment"!==d.Ms.rules[f].type){var h=new _geo.c.dc.efa,l;for(l=0;l<d.Ms.rules[f].zQ.length;l++)h.yg(d.Ms.rules[f].zQ[l].eTa,d.Ms.rules[f].zQ[l].value,null);for(l=0;l<d.Ms.rules[f].XU.length;l++){var k=h.clone().Qb(d.Ms.rules[f].XU[l]);b.ac().yg(null,k,d.Ms.rules[f].XU[l]);this.Co().yg(k,d.Ms.rules[f].XU[l])}}}};return b}();
_geo.c.dc.Gb.eKb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="polyline"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.PolylineParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"points"),d=e.split(/[ ,\n\r\t]/),f=[],e=this.getAttribute(a,"id"),h=this.getAttribute(a,"class"),l=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa,k;for(k=0;k<d.length;k++)""!==
d[k]&&f.push(d[k]);var d=[],m=[];for(k=0;k<f.length;k++){var q=this.Zt(f[k++],0),p=this.as(f[k],0);d.push(q);m.push(p)}f=(new _geo.c.V.$.hr({x:d,y:m})).Ae(this.Be(e)?e:null).Qb(this.jd).To(this.jd).pe(this.Be(h)?h:null).je(l);k=this.qO(a,b);q=new _geo.c.dc.bv(b.Zq(),l,k,f,b.ZE(),f,b.tD());p=this.KQ(q);null!=p.fillstyle&&p.fillstyle instanceof _geo.c.attributes.Ha&&(f=(new _geo.c.V.$.If({x:d,y:m})).Ae(this.Be(e)?e:null).Qb(this.jd).To(this.jd).pe(this.Be(h)?h:null).je(l),q=new _geo.c.dc.bv(b.Zq(),
l,k,f,b.ZE(),f,b.tD()),p=this.KQ(q));f.ka(p);this.zJ(a,q);this.N0(f,a,q);return f};return b}();
_geo.c.dc.Gb.IMb=function(){function b(){_geo.c.dc.lM.call(this);this.jd="use"}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.parsers.UseParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"xlink:href");null==e&&_geo.c.log('<use> should containes "xlink:href" attribute');var d=this.Co().Rra(e);null==d&&_geo.c.log('There is no reference "'+e+'" found');var f=this.getAttribute(a,"transform"),
e=null;null!=f&&""!==f&&(e=this.AJ(f));var h=this.Zt(this.getAttribute(a,"x"),0),l=this.as(this.getAttribute(a,"y"),0),f=this.Zt(this.getAttribute(a,"height"),0),k=this.as(this.getAttribute(a,"width"),0),k=new _geo.c.f.Rect(h,l,h+k,l+f),f=new _geo.c.f.Fa;if(0!==h||0!==l)f=_geo.c.f.Fa.Mj(h,l);h=this.getAttribute(d,"viewBox");l=null;null!=h&&""!==h&&(l=this.Uta(h),null!=l&&(f=_geo.c.f.Fa.Sf(l,k,!1,!1,!1)));h=this.rBa(e,b.$a());l=this.qO(a,b);k=[];h=new _geo.c.dc.bv(k,h,l,b.RI(),b.ZE(),null,b.tD());
d=this.Co().Ny(d,h);d instanceof _geo.c.V.Node&&(d instanceof _geo.c.V.Uo&&(f=this.rBa(f,e),d.je(f)),b.RAa(d));return d};return b}();
_geo.c.dc.Gb.HJb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="path"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.PathParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"id"),d=this.getAttribute(a,"class"),f=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa,e=this.USa(this.getAttribute(a,"d")).Ae(this.Be(e)?e:null).Qb(this.jd).To(this.jd).pe(this.Be(d)?
d:null).je(f),f=new _geo.c.dc.bv(b.Zq(),f,b.ac(),e,b.ZE(),e,b.tD()),h=this.qO(a,f),d=this.KQ(h,f),h=h.ac("fill-rule");e.ka(d);this.Be(h)&&null!=e.Bb()&&"evenodd"===h&&e.Bb().dZ(!0);this.zJ(a,f);return this.N0(e,a,f)};return b}();
_geo.c.dc.Gb.xIb=function(){function b(){_geo.c.dc.fz.call(this);this.jd="line"}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.LineParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.Zt(this.getAttribute(a,"x1"),0),d=this.as(this.getAttribute(a,"y1"),0),f=this.Zt(this.getAttribute(a,"x2"),0),h=this.as(this.getAttribute(a,"y2"),0),l=this.getAttribute(a,"id"),k=this.getAttribute(a,"class"),
m=this.AJ(this.getAttribute(a,"transform"))||new _geo.c.f.Fa,e=(new _geo.c.V.$.Jr(new _geo.c.f.sa(e,d),new _geo.c.f.sa(f,h))).Ae(this.Be(l)?l:null).Qb(this.jd).To(this.jd).pe(this.Be(k)?k:null).je(m),d=this.qO(a,b),m=new _geo.c.dc.bv(b.Zq(),m,d,e,b.ZE(),e,b.tD()),d=this.KQ(m);e.ka(d);this.zJ(a,m);return this.N0(e,a,m)};return b}();
_geo.c.dc.Gb.QEb=function(){function b(){_geo.c.dc.Gb.Yu.call(this);this.jd="a"}_geo.c.na(b,_geo.c.dc.Gb.Yu);_geo.c.ja(b,"geotoolkit.svg.parsers.AParser");b.prototype.getName=function(){return this.jd};return b}();_geo.c.dc.Gb.dlc=function(){function b(){_geo.c.dc.Gb.Yu.call(this);this.jd="symbol"}_geo.c.na(b,_geo.c.dc.Gb.Yu);_geo.c.ja(b,"geotoolkit.svg.parsers.SymbolParser");return b}();
_geo.c.dc.Gb.n4=function(){function b(){_geo.c.dc.fz.call(this);this.jd="text";this.al=this.dk=null}function a(a,b){for(var d="",f=a.firstChild;null!==f;f=f.nextSibling)f.nodeType===_geo.c.window.Node.TEXT_NODE&&(d+=f.nodeValue);b.Ec(d);return d}_geo.c.na(b,_geo.c.dc.fz);_geo.c.ja(b,"geotoolkit.svg.parsers.TextParser");b.prototype.KQ=function(a,b){var d=_geo.c.dc.lM.prototype.KQ.call(this,a,b);this.dr(d,a);d.fillstyle=null;d.linestyle=null;return d};b.prototype.dr=function(a,b){a.textstyle=this.kt(b,
a.textstyle||new _geo.c.attributes.kb);a.textstyle&&a.fillstyle&&a.textstyle.ed(a.fillstyle.Kc())};b.prototype.parse=function(b,e){if(!b)throw Error("Passed node is not valid");if(!e)throw Error("Passed context is not valid");var d=this.Zt(this.getAttribute(b,"x"),0),f=this.as(this.getAttribute(b,"y"),0),h=this.RU(this.getAttribute(b,"width"),100),l=this.RY(this.getAttribute(b,"height"),100),k=this.getAttribute(b,"text-anchor");switch(k){case "middle":k=_geo.c.f.Ca.ub;break;case "end":k=_geo.c.f.Ca.eh;
break;default:k=_geo.c.f.Ca.Ej}var m=this.getAttribute(b,"id"),q=this.getAttribute(b,"class"),p=this.AJ(this.getAttribute(b,"transform"))||new _geo.c.f.Fa,d=(new _geo.c.V.$.Text("",d,f,h,l,new _geo.c.attributes.kb,!1)).Ae(this.Be(m)?m:null).Qb(this.jd).To(this.jd).pe(this.Be(q)?q:null).je(p).Bj(_geo.c.V.$.Text.ef.Gr).Ld(k);a(b,d);f=this.qO(b,e);p=new _geo.c.dc.bv(e.Zq(),p,f,d,e.ZE(),d,e.tD());f=this.KQ(p);d.ka(f);this.zJ(b,p);return this.N0(d,b,p)};return b}();
_geo.c.dc.Gb.VFb=function(){function b(){_geo.c.dc.lM.call(this);this.jd="clipPath"}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.parsers.ClipPathParser");b.prototype.parse=function(a,b){function e(a){if("function"===typeof a.ce)a=a.ce();else if(a instanceof _geo.c.V.$.KF){var b=a.ha(),d=b.rd(),e=b.td();a=b.ba()/2;b=b.da()/2;d="M"+(d-a)+","+e+("a"+a+","+b+" 0 1,0 "+2*a+",0");d+="a"+a+","+b+" 0 1,0 "+-2*a+",0";a=m.USa(d).ce()}else if("function"===typeof a.ha)a=a.ha();else return;k?a&&"function"===
typeof k.ha&&"function"===typeof a.ha&&(k=k.ha().zi(a.ha())):k=a}if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");for(var d=[],f=this.AJ(this.getAttribute(a,"transform")),f=this.rBa(f,b.$a()),h=this.qO(a,b),h=new _geo.c.dc.bv(d,f,h,b.RI()),l=a.firstChild;null!==l;l=l.nextSibling)l.nodeType===_geo.c.window.Node.ELEMENT_NODE&&this.Co().Ny(l,h);if(0===d.length)return null;for(var k=null,m=this,h=0;h<d.length;++h)d[h]&&e(d[h]);return k?f.transform(k):null};
return b}();
_geo.c.dc.Gb.y3=function(){function b(){_geo.c.dc.lM.call(this)}_geo.c.na(b,_geo.c.dc.lM);_geo.c.ja(b,"geotoolkit.svg.AnimationParser");b.Kx={Ka:"x",Na:"y",Dhb:"w",afb:"h",iIc:"angle",v9:"exact"};b.Z9={TJ:1,iA:2,Ieb:4};b.prototype.Sxb=function(a){a=this.getAttribute(a,"fill");return"freeze"===a?_geo.c.Ab.Qla.pXa:_geo.c.Ab.Qla.Wea};b.prototype.Wxb=function(a){var b=this.getAttribute(a,"values"),e=[];this.Be(b)?b.split(";").forEach(function(a){e.push(_geo.c.f.pj.Nha(a.trim()))}):(b=this.getAttribute(a,"from"),
a=this.getAttribute(a,"to"),this.Be(b)&&e.push(_geo.c.f.pj.Nha(b.split(";")[0].trim())),this.Be(a)&&e.push(_geo.c.f.pj.Nha(a.split(";")[0].trim())));return e};b.prototype.cyb=function(a){var b=this.getAttribute(a,"repeatCount");a=this.getAttribute(a,"repeatDur");return this.Be(b)||this.Be(a)?"indefinite"===b||"indefinite"===a?window.Infinity:Number.parseInt(b):1};b.prototype.G$a=function(a){var b=this.getAttribute(a,"values"),e=[];this.Be(b)?b.split(";").forEach(function(a){e.push(a.trim())}):(b=
this.getAttribute(a,"from"),a=this.getAttribute(a,"to"),this.Be(b)&&e.push(b.trim()),this.Be(a)&&e.push(a.trim()));return e};b.prototype.SSa=function(a,b){var e=this.getAttribute(b,"additive");if(this.Be(e))switch(e){case "sum":a.gNb=_geo.c.Ab.dHa.Axa;break;case "replace":a.gNb=_geo.c.Ab.dHa.Ox;break}e=this.getAttribute(b,"accumulate");if(this.Be(e))switch(e){case "sum":a.l_a=_geo.c.Ab.Nla.Axa;break;case "none":a.l_a=_geo.c.Ab.Nla.cf;break}a.cI=this.Sxb(b);a.nr=this.getAttribute(b,"id");a.M2a=this.cyb(b);
this.Xxb(b,a);if((e=this.getAttribute(b,"calcMode"))&&this.Be(e.trim()))switch(e){case "discrete":a.K4=_geo.c.Ab.FF.PV;break;case "spline":a.K4=_geo.c.Ab.FF.TH;break;case "paced":a.K4=_geo.c.Ab.FF.MIa;break;default:a.K4=_geo.c.Ab.FF.gj;break}};b.prototype.hka=function(a,g,e){a=a.trim();switch(g){case b.Kx.Ka:return this.Zt(a,0)*(e&&e.$c&&e.$c.Rb()||1);case b.Kx.Na:return this.as(a,0)*(e&&e.$c&&e.$c.hc()||1);case b.Kx.Dhb:return this.RU(a,0)*(e&&e.$c&&e.$c.Rb()||1);case b.Kx.afb:return this.RY(a,0)*
(e&&e.$c&&e.$c.hc()||1);default:return Number.parseFloat(a)}};b.prototype.$xb=function(a){var g=[];a=this.getAttribute(a,"keyTimes");return this.Be(a)?(a.split(";").forEach(function(a){g.push(this.hka(a,b.Kx.v9,null))}.bind(this)),g):null};b.prototype.SY=function(a,g,e){var d=[],f=this.getAttribute(a,"values");if(this.Be(f))f.split(";").forEach(function(a){d.push(this.hka(a.trim(),b.Kx.v9,e))}.bind(this));else{var f=0,h=this.getAttribute(a,"from"),l=this.getAttribute(a,"to");a=this.getAttribute(a,
"by");if(this.Be(h))f=this.hka(h.split(";")[0].trim(),b.Kx.v9,e);else{var h=new _geo.c.f.Rect,k=e.Ub();k&&(h=k.yj(null,!1));switch(g){case b.Kx.Ka:f=h.x;break;case b.Kx.Na:f=h.y;break;case b.Kx.Dhb:f=h.width;break;case b.Kx.afb:f=h.height;break}}d.push(f);if(this.Be(l))g=this.hka(l.split(";")[0].trim(),b.Kx.v9,e),d.push(g);else if(this.Be(a))g=this.hka(a.split(";")[0].trim(),b.Kx.v9,e),d.push(f+g);else throw Error("NoValuesAttribute");}return d};b.prototype.WSa=function(a){var b=[],e=this.getAttribute(a,
"values");if(this.Be(e))e.split(";").forEach(function(a){a=this.sEa(a);0!==a.length&&(1<a.length?b.push(new _geo.c.f.sa(a[0].yn(),a[1].yn())):b.push(new _geo.c.f.sa(a[0].yn(),a[0].yn())))}.bind(this));else{var d=this.getAttribute(a,"from"),f=this.getAttribute(a,"to"),e=new _geo.c.f.sa;this.Be(d)&&(e=this.sEa(this.getAttribute(a,"from")),e=0===e.length?new _geo.c.f.sa(1,1):1<e.length?new _geo.c.f.sa(e[0].yn(),e[1].yn()):new _geo.c.f.sa(e[0].yn(),e[0].yn()));if(this.Be(f))a=this.sEa(this.getAttribute(a,
"to")),a=0===a.length?new _geo.c.f.sa(1,1):1<a.length?new _geo.c.f.sa(a[0].yn(),a[1].yn()):new _geo.c.f.sa(a[0].yn(),a[0].yn());else return b;b.push(e);b.push(a)}return b};b.prototype.dyb=function(a){var b=[],e=this.getAttribute(a,"values");if(this.Be(e))e.split(";").forEach(function(a){b.push(this.gRa(a))}.bind(this));else if(e=this.getAttribute(a,"from"),a=this.getAttribute(a,"to"),this.Be(e)&&b.push(this.gRa(e)),this.Be(a))b.push(this.gRa(a));else throw Error("NoValuesAttribute");return b};b.prototype.y7b=
function(a){if(!this.Be(a)){var b=this.Co().U6();a=b.h8(a);switch(a.sq()){case a.sq("CssMillisecond"):return a.yn();case a.sq("CssSecond"):return 1E3*a.yn();case a.sq("CssMinute"):return 6E4*a.yn();case a.sq("CssHour"):return 36E5*a.yn();default:return a.yn()}}return 0};b.prototype.sEa=function(a){var b=[];if(this.Be(a)){var e=this.Co().U6();a.split(",").forEach(function(a){b.push(e.h8(a))})}return b};b.prototype.Xxb=function(a,b){if(b&&a){var e={mra:b,Nt:this.getAttribute(a,"begin"),end:this.getAttribute(a,
"end"),a6a:this.getAttribute(a,"dur")};this.eyb(e);if(0===b.FP)throw Error("WrongEndTime");}};b.prototype.gRa=function(a){var b=[];a=this.sEa(a.trim());for(var e=0;3>e;e++)b[e]=e>=a.length?0:a[e].yn();return b};b.prototype.eyb=function(a){this.Be(a.Nt)?this.setTime(a,b.Z9.TJ):a.mra.Nt=0;this.Be(a.a6a)?this.setTime(a,b.Z9.Ieb):a.mra.a6a=0;this.Be(a.end)&&this.setTime(a,b.Z9.iA)};b.prototype.setTime=function(a,g){var e=0,d;switch(g){case b.Z9.TJ:d=a.Nt;break;case b.Z9.Ieb:d=a.a6a;break;case b.Z9.iA:d=
a.end;break}var f=this.Co().U6();d=f.h8(d);switch(d.sq()){case d.sq("CssMillisecond"):e=d.yn();break;case d.sq("CssSecond"):e=1E3*d.yn();break;case d.sq("CssMinute"):e=6E4*d.yn();break;case d.sq("CssHour"):e=36E5*d.yn();break;case d.sq("CssStringValue"):e=d.getStringValue();break}switch(g){case b.Z9.TJ:a.mra.$F=e;a.Nt=null;break;case b.Z9.Ieb:a.mra.Wfa=e;a.a6a=null;break;case b.Z9.iA:a.sKc=!0;a.mra.Wfa=0<e-a.mra.$F?e-a.mra.$F:0;a.end=null;break}};return b}();
_geo.c.dc.Gb.XVa=function(){function b(){_geo.c.dc.Gb.y3.call(this);this.jd="animate"}var a=_geo.c.dc.Gb.y3;_geo.c.na(b,_geo.c.dc.Gb.y3);_geo.c.ja(b,"geotoolkit.svg.parsers.AnimateParser");b.prototype.parse=function(b,e){if(!b)throw Error("Passed node is not valid");if(!e)throw Error("Passed context is not valid");var d=e.Ub();if(d){var f=this.getAttribute(b,"attributeName"),h=null;if(this.Be(f)){h=_geo.c.Ab.Ad.he.ib().xBa({attributeName:f});switch(f){case "x":case "cx":h.kh(this.SY(b,a.Kx.Ka,e));
break;case "y":case "cy":h.kh(this.SY(b,a.Kx.Ka,e));break;case "width":h.kh(this.SY(b,a.Kx.Dhb,e));break;case "height":h.kh(this.SY(b,a.Kx.afb,e));break;case "ry":case "rx":h.kh(this.SY(b,a.Kx.Ka,e));break;case "stroke-opacity":case "fill-opacity":case "opacity":h.kh(this.SY(b,a.Kx.v9,e));break;case "fill":case "stroke":h.kh(this.Wxb(b));break;case "x1":case "x2":h.kh(this.SY(b,a.Kx.Ka,e));break;case "y1":case "y2":h.kh(this.SY(b,a.Kx.Na,e));break;case "visibility":h.kh(this.G$a(b));break;case "stroke-width":h.kh(this.SY(b,
a.Kx.v9,e));break;case "font-size":h.kh(this.SY(b,a.Kx.v9,e));break;case "int:text":h.kh(this.G$a(b));break;default:throw Error("Not supported animated attribute: "+f);}this.SSa(h,b);(f=this.$xb(b))&&2<=f.length&&h.sac(f);f=d.MPa()||new _geo.c.attributes.JZ;d.gFa(f);f.t4a(h)}}};return b}();
_geo.c.dc.Gb.cFb=function(){function b(){_geo.c.dc.Gb.y3.call(this);this.jd="animateColor"}_geo.c.na(b,_geo.c.dc.Gb.XVa);_geo.c.ja(b,"geotoolkit.svg.parsers.AnimateColorParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=this.getAttribute(a,"attributeName");!this.Be(e)||"fill"!==e&&"stroke"!==e?null:_geo.c.dc.Gb.XVa.prototype.parse.call(this,a,b)};return b}();
_geo.c.dc.Gb.GJb=function(){function b(a){this.xs=[];this.Jga=[];this.cLa=a;this.Gj;this.I2a=0}var a=10;_geo.c.ja(b,"geotoolkit.svg.parsers.PathInterpolator");b.prototype.aC=function(){return Math.min(this.xs.length,this.Jga.length)};b.prototype.reset=function(){this.I2a=0;this.xs=[];this.Jga=[]};b.prototype.nqc=function(){this.Jga[this.Jga.length-1]=_geo.c.Sa.yf.Vi.$R};b.prototype.rqc=function(a){this.Gj=new _geo.c.f.sa(a);this.xs.push(this.Gj);this.Jga.push(_geo.c.Sa.yf.Vi.TF)};b.prototype.pTb=
function(a){this.Gj=new _geo.c.f.sa(a);this.xs.push(this.Gj);this.Jga.push(_geo.c.Sa.yf.Vi.hK)};b.prototype.fOa=function(b,e,d){this.I2a++;var f=this.Lh(b,this.Gj,d),h=this.Lh(e,this.Gj,d);if(f+h<=this.cLa||this.I2a>=a)this.pTb(d);else{f=new _geo.c.f.sa(d);h=new _geo.c.f.sa((this.Gj.ga()+b.ga())/2,(this.Gj.ea()+b.ea())/2);d=new _geo.c.f.sa((e.ga()+d.ga())/2,(e.ea()+d.ea())/2);var l=new _geo.c.f.sa(h.ga()/2+(b.ga()+e.ga())/4,h.ea()/2+(b.ea()+e.ea())/4);b=new _geo.c.f.sa((b.ga()+e.ga())/4+d.ga()/2,
(b.ea()+e.ea())/4+d.ea()/2);e=new _geo.c.f.sa((l.ga()+b.ga())/2,(l.ea()+b.ea())/2);this.fOa(h,l,e);this.fOa(b,d,f)}this.I2a--};b.prototype.Lh=function(a,b,d){var f=_geo.c.f.sa.Jm(b,d);return 0!==f?Math.abs((b.x-a.x)*(d.y-a.y)-(b.y-a.y)*(d.x-a.x))/f:0};return b}();
_geo.c.dc.Gb.dFb=function(){function b(){_geo.c.dc.Gb.y3.call(this);this.jd="animateMotion"}_geo.c.na(b,_geo.c.dc.Gb.y3);_geo.c.ja(b,"geotoolkit.svg.parsers.AnimateMotionParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=b.Ub();if(e){var d=_geo.c.Ab.Ad.he.ib().xBa({attributeName:"path"}),f=this.getAttribute(a,"path");if(this.Be(f))f=this.USa(f),this.scb(d,f);else if(1<(f=this.WSa(a)).length)f.forEach(function(a){d.lc(a)});
else if(a.childNodes.length){var h=[];b.Zq().forEach(function(a){h.push(a)});f=new _geo.c.dc.bv(h,new _geo.c.f.Fa);this.zJ(a,f);f.Zq().forEach(function(a){this.scb(d,a)}.bind(this))}if(!d.exc())throw Error("NoValuesAttribute");d.maa=_geo.c.Ab.Ad.Swa.r_.Tv;f=this.getAttribute(a,"rotate");if(this.Be(f))switch(f){case "auto":d.maa=_geo.c.Ab.Ad.Swa.r_.wB;break;case "auto-reverse":d.maa=_geo.c.Ab.Ad.Swa.r_.lHa;break;default:d.SMa=this.hka(f,_geo.c.dc.Gb.y3.Kx.v9,b)*(Math.PI/180);break}else d.SMa=0;f=this.getAttribute(a,
"accumulate");if(this.Be(f))switch(f){case "sum":d.l_a=_geo.c.Ab.Nla.Axa;break;case "none":d.l_a=_geo.c.Ab.Nla.cf;break}this.SSa(d,a);f=e.MPa()||new _geo.c.attributes.JZ;e.gFa(f);f.t4a(d)}};b.prototype.scb=function(a,b){var e=new _geo.c.dc.Gb.GJb(.1),d=[new _geo.c.f.sa,new _geo.c.f.sa,new _geo.c.f.sa];b=b.ce();var f;for(f=0;f<b.ud();f++){var h=b.Si(f);switch(h.type){case _geo.c.Sa.yf.Vi.$R:e.nqc();break;case _geo.c.Sa.yf.Vi.TF:e.rqc(d[0].lb(h.x,h.y));break;case _geo.c.Sa.yf.Vi.hK:e.pTb(d[0].lb(h.x,
h.y));break;case _geo.c.Sa.yf.Vi.QO:e.fOa(d[0].lb(h.cp1x,h.cp1y),d[1].lb(h.cp2x,h.cp2y),d[2].lb(h.x,h.y));break}}var d=e.xs,h=[new _geo.c.f.sa],l=[0],k=0,m=new _geo.c.f.sa,q=new _geo.c.f.sa,p=_geo.c.Sa.yf.Vi.TF;for(f=0;f<e.aC();f++){switch(e.Jga[f]){case _geo.c.Sa.yf.Vi.TF:_geo.c.Sa.yf.Vi.TF===p&&0<h.length&&(h.pop(),l.pop());h.push(new _geo.c.f.sa(d[f]));l.push(0);q=d[f];m=d[f];break;case _geo.c.Sa.yf.Vi.hK:m=_geo.c.f.sa.Jm(m,d[f]);l.push(m);h.push(new _geo.c.f.sa(d[f]));k+=m;m=d[f];break;case _geo.c.Sa.yf.Vi.$R:m=
_geo.c.f.sa.Jm(m,d[f]);l.push(m);h.push(new _geo.c.f.sa(d[f]));k+=m;m=_geo.c.f.sa.Jm(q,d[f]);h.push(new _geo.c.f.sa(q));l.push(m);k+=m;m=q;break}p=e.Jga[f]}for(f=1;f<l.length;f++)l[f]=l[f-1]+l[f]/k;a.kh(h);a.sac(l)};return b}();
_geo.c.dc.Gb.eFb=function(){function b(){_geo.c.dc.Gb.y3.call(this);this.jd="animateTransform"}_geo.c.na(b,_geo.c.dc.Gb.y3);_geo.c.ja(b,"geotoolkit.svg.parsers.AnimateTransformParser");b.prototype.parse=function(a,b){if(!a)throw Error("Passed node is not valid");if(!b)throw Error("Passed context is not valid");var e=b.Ub();if(e){var d=this.getAttribute(a,"attributeName"),f=this.getAttribute(a,"type");if("transform"===d||"patternTransform"===d||"gradientTransform"===d){d=_geo.c.Ab.Ad.he.ib().xBa({attributeName:d,
type:f});switch(f){case "scale":var f=this.WSa(a),h;for(h in f)d.lc(f[h]);break;case "translate":d.kh(this.WSa(a));break;case "rotate":d.kh(this.dyb(a));break}this.SSa(d,a);h=e.MPa()||new _geo.c.attributes.JZ;e.gFa(h);h.t4a(d)}}};return b}();
(function(){var b="geotoolkit",a=_geo.c.hx,g=_geo.c.gx,e=null,d=null;g(e=_geo.c.dc.fS.prototype,"setDocumentParser",e.wFa,{wFa:0});g(e,"getDocumentParser",e.Co,{Co:0});g(e,"getName",e.getName,{getName:0});g(e,"parse",e.parse,{parse:0});g(e=_geo.c.dc.lM.prototype,"getDocumentParser",e.Co,{Co:0});g(e,"setDocumentParser",e.wFa,{wFa:0});g(e,"angle",e.Fz,{Fz:0});g(e,"getAttribute",e.getAttribute,{getAttribute:0});g(e,"parseAttribute",e.qO,{qO:0});g(e,"parseChildren",e.zJ,{zJ:0});g(e,"parsePath",e.USa,
{USa:0});g(e,"endpointToCenter",e.Lqb,{Lqb:0});g(e,"quadTo",e.DEa,{DEa:0});g(e,"splitQuadToLine",e.$Ua,{$Ua:0});g(e,"dist",e.IBa,{IBa:0});g(e,"parseCoordinateX",e.Zt,{Zt:0});g(e,"parseCoordinateY",e.as,{as:0});g(e,"parseHeight",e.RY,{RY:0});g(e,"parseWidth",e.RU,{RU:0});g(e,"parseCoordinate",e.Vta,{Vta:0});g(e,"parseBox",e.Uta,{Uta:0});g(e,"decodeLUnit",e.fra,{fra:0});g(e,"parseClip",e.RSa,{RSa:0});g(e,"validateString",e.Be,{Be:0});g(e,"parseTransformation",e.AJ,{AJ:0});g(e,"parseNumber",e.rO,{rO:0});
g(e,"getParamTokenizer",e.p7,{p7:0});g(e,"concatenateTransformation",e.rBa,{rBa:0});g(e,"getGraphicAttributes",e.KQ,{KQ:0});g(e,"setLineScalable",e.zbb,{zbb:0});g(e,"getColorWithOpacity",e.Z6a,{Z6a:0});g(e,"setFillOpacity",e.ebb,{ebb:0});g(e,"setOpacityToLine",e.Nbb,{Nbb:0});g(e,"decodeLineCap",e.Mpb,{Mpb:0});g(e,"decodeLineJoin",e.Npb,{Npb:0});g(e,"parseLength",e.C$a,{C$a:0});g(e,"getStyleAttribute",e.tU,{tU:0});g(e,"decodeFill",e.Lpb,{Lpb:0});g(e,"decodeLinearGradientFill",e.Opb,{Opb:0});g(e,"decodeRadialGradientFill",
e.Qpb,{Qpb:0});g(e,"parsePercent",e.s2,{s2:0});g(e,"decodePatternFill",e.Ppb,{Ppb:0});g(e,"groupToImage",e.e9a,{e9a:0});g(e,"getFont",e.kt,{kt:0});g(e=_geo.c.dc.IJb.prototype,"nextCommand",e.mxb,{mxb:0});g(e,"nextNumber",e.yJ,{yJ:0});g(e=_geo.c.dc.efa.prototype,"setName",e.Qb,{Qb:0});g(e,"toString",e.toString,{toString:0});g(e,"setStyle",e.yg,{yg:0});g(e,"getStyle",e.ac,{ac:0});g(e,"merge",e.Jy,{Jy:0});g(e,"clone",e.clone,{clone:0});a(b+".svg.SVGParser",(d=_geo.c.dc).ena);g(e=_geo.c.dc.ena.prototype,
"scalablePatterns",e.zzb,{zzb:0});g(e,"setScalablePatterns",e.sbc,{sbc:0});g(e,"parse",e.parse,{parse:0});g(e,"getSvgMetaInfo",e.T2b,{T2b:0});g(e=_geo.c.dc.bv.prototype,"setRootGroup",e.pCb,{pCb:0});g(e,"getRootGroup",e.tD,{tD:0});g(e,"getTransformation",e.$a,{$a:0});g(e,"setTransformation",e.sc,{sc:0});g(e,"getShapes",e.Zq,{Zq:0});g(e,"getStyle",e.ac,{ac:0});g(e,"setStyle",e.yg,{yg:0});g(e,"getArea",e.RI,{RI:0});g(e,"setArea",e.S9b,{S9b:0});g(e,"getClipping",e.ZE,{ZE:0});g(e,"setClipping",e.Qab,
{Qab:0});g(e,"getShape",e.Ub,{Ub:0});g(e,"addShape",e.RAa,{RAa:0});g(e,"pushShape",e.xyb,{xyb:0});g(e,"pushStyle",e.jTa,{jTa:0});g(e=_geo.c.dc.fz.prototype,"appendShape",e.N0,{N0:0});g(e,"appendClipping",e.Tnb,{Tnb:0});g(e,"makeMarkers",e.Owb,{Owb:0});g(e=_geo.c.dc.EJb.prototype,"beginPath",e.beginPath,{beginPath:0});g(e,"bezierCurveTo",e.bezierCurveTo,{bezierCurveTo:0});g(e,"moveTo",e.moveTo,{moveTo:0});g(e,"getPath",e.F1b,{F1b:0});g(e,"closePath",e.closePath,{closePath:0});a(b+".svg.Util",d.gc);
a(b+".svg.SvgDataProvider",d.JLb);g(e=_geo.c.dc.JLb.prototype,"loadXmlData",e.Q5b,{Q5b:0});g(e=_geo.c.dc.blc.prototype,"render",e.Aa,{Aa:0});a(b+".svg.SvgGroup",d.X9);g(e=_geo.c.dc.X9.prototype,"addChild",e.Ia,{Ia:0});g(e,"insertChild",e.bh,{bh:0});g(e,"removeChild",e.removeChild,{removeChild:0});g(e,"updateState",e.Qa,{Qa:0});g(e,"clearChildren",e.Gh,{Gh:0});g(e=_geo.c.dc.Gb.uKb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.yZa.prototype,"getMetaInfo",e.Ntb,{Ntb:0});g(e,"parse",e.parse,{parse:0});
g(e,"calculateViewBoxTransformation",e.GUb,{GUb:0});g(e=_geo.c.dc.Gb.UFb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.dKb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.Yu.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.BGb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.VGb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.GXa.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.HLb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.eKb.prototype,"parse",e.parse,
{parse:0});g(e=_geo.c.dc.Gb.IMb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.HJb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.xIb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.QEb.prototype,"getName",e.getName,{getName:0});g(e=_geo.c.dc.Gb.n4.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.VFb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.y3.prototype,"parseAnimationFill",e.Sxb,{Sxb:0});g(e,"parseColorValues",e.Wxb,{Wxb:0});g(e,"parseRepeatCount",e.cyb,{cyb:0});
g(e,"parseStringValues",e.G$a,{G$a:0});g(e,"parseCommonEffectSettings",e.SSa,{SSa:0});g(e,"parseDoubleValue",e.hka,{hka:0});g(e,"parseKeyTimes",e.$xb,{$xb:0});g(e,"parseNumberValues",e.SY,{SY:0});g(e,"parsePointValues",e.WSa,{WSa:0});g(e,"parseRotationPointValues",e.dyb,{dyb:0});g(e,"parseTime",e.y7b,{y7b:0});g(e,"parseValues",e.sEa,{sEa:0});g(e,"parseEffectRunTime",e.Xxb,{Xxb:0});g(e,"getRotationPoint",e.gRa,{gRa:0});g(e,"parseTimeValue",e.eyb,{eyb:0});g(e,"setTime",e.setTime,{setTime:0});g(e=_geo.c.dc.Gb.XVa.prototype,
"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.cFb.prototype,"parse",e.parse,{parse:0});g(e=_geo.c.dc.Gb.GJb.prototype,"getCount",e.aC,{aC:0});g(e,"addBezierToSegment",e.fOa,{fOa:0});g(e,"distance",e.Lh,{Lh:0});g(e=_geo.c.dc.Gb.dFb.prototype,"parse",e.parse,{parse:0});g(e,"setupPath",e.scb,{scb:0});g(e=_geo.c.dc.Gb.eFb.prototype,"parse",e.parse,{parse:0})})();

    return _geo.geotoolkit.svg;
}(_geo));
/* eslint-enable */
/* tslint:enable */